// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double4x3
    {

        public static double3x4 Transpose(double4x3 value)
        {
            return new double3x4(new double4(value.c0.x, value.c1.x, value.c2.x, value.c3.x), new double4(value.c0.y, value.c1.y, value.c2.y, value.c3.y), new double4(value.c0.z, value.c1.z, value.c2.z, value.c3.z));
        }

        public static double4x3 MatrixCompMult(double4x3 left, double4x3 right)
        {
            return new double4x3(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2, left.c3 * right.c3);
        }

        public static double4x3 OuterProduct(double3 c, double4 r)
        {
            return new double4x3(c * r.x, c * r.y, c * r.z, c * r.w);
        }
    }
}
