// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A column-major 2x3 matrix represented by 2 double3 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct double2x3 : IEquatable<double2x3>
    {

        /// <summary>Column 0.</summary>
        public double3 c0;

        /// <summary>Column 1.</summary>
        public double3 c1;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly double2x3 zero = new double2x3(double3.zero, double3.zero);

        /// <summary>Creates a matrix from its columns in column-major order.</summary>
        public double2x3(double3 c0, double3 c1)
        {
            this.c0 = c0;
            this.c1 = c1;
        }

        /// <summary>Creates a matrix with value on the diagonal and zero elsewhere.</summary>
        public double2x3(double value)
        {
            c0 = new double3(value, 0.0, 0.0);
            c1 = new double3(0.0, value, 0.0);
        }

        /// <summary>Creates a matrix from row-major named components in mathematical order.</summary>
        public double2x3(double m11, double m12, double m21, double m22, double m31, double m32)
        {
            c0 = new double3(m11, m21, m31);
            c1 = new double3(m12, m22, m32);
        }

        /// <summary>Creates a double2x3 from a float2x2 using GLSL matrix conversion rules.</summary>
        public double2x3(float2x2 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, 0.0);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a float2x3 using GLSL matrix conversion rules.</summary>
        public double2x3(float2x3 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a float2x4 using GLSL matrix conversion rules.</summary>
        public double2x3(float2x4 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a float3x2 using GLSL matrix conversion rules.</summary>
        public double2x3(float3x2 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, 0.0);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a float3x3 using GLSL matrix conversion rules.</summary>
        public double2x3(float3x3 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a float3x4 using GLSL matrix conversion rules.</summary>
        public double2x3(float3x4 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a float4x2 using GLSL matrix conversion rules.</summary>
        public double2x3(float4x2 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, 0.0);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a float4x3 using GLSL matrix conversion rules.</summary>
        public double2x3(float4x3 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a float4x4 using GLSL matrix conversion rules.</summary>
        public double2x3(float4x4 value)
        {
            c0 = new double3((double)value.c0.x, (double)value.c0.y, (double)value.c0.z);
            c1 = new double3((double)value.c1.x, (double)value.c1.y, (double)value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double2x2 using GLSL matrix conversion rules.</summary>
        public double2x3(double2x2 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, 0.0);
            c1 = new double3(value.c1.x, value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a double2x3 using GLSL matrix conversion rules.</summary>
        public double2x3(double2x3 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double2x4 using GLSL matrix conversion rules.</summary>
        public double2x3(double2x4 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double3x2 using GLSL matrix conversion rules.</summary>
        public double2x3(double3x2 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, 0.0);
            c1 = new double3(value.c1.x, value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a double3x3 using GLSL matrix conversion rules.</summary>
        public double2x3(double3x3 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double3x4 using GLSL matrix conversion rules.</summary>
        public double2x3(double3x4 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double4x2 using GLSL matrix conversion rules.</summary>
        public double2x3(double4x2 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, 0.0);
            c1 = new double3(value.c1.x, value.c1.y, 0.0);
        }

        /// <summary>Creates a double2x3 from a double4x3 using GLSL matrix conversion rules.</summary>
        public double2x3(double4x3 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Creates a double2x3 from a double4x4 using GLSL matrix conversion rules.</summary>
        public double2x3(double4x4 value)
        {
            c0 = new double3(value.c0.x, value.c0.y, value.c0.z);
            c1 = new double3(value.c1.x, value.c1.y, value.c1.z);
        }

        /// <summary>Returns a column using zero-based indexing.</summary>
        public double3 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public double2 GetRow(int index)
        {
            return index switch { 0 => new double2(c0.x, c1.x), 1 => new double2(c0.y, c1.y), 2 => new double2(c0.z, c1.z), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public double GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, double value)
        {
            if ((uint)column >= 2u || (uint)row >= 3u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; }
        }

        public double M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public double M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public double M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public double M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public double M31
        {
            get => c0.z;
            set => c0.z = value;
        }

        public double M32
        {
            get => c1.z;
            set => c1.z = value;
        }

        public bool Equals(double2x3 other)
        {
            return c0 == other.c0 && c1 == other.c1;
        }

        public override bool Equals(object? obj)
        {
            return obj is double2x3 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}; {M21}, {M22}; {M31}, {M32}]");
        }
    }
}
