// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3x3
    {

        public static double3x3 operator +(double3x3 left, double3x3 right)
        {
            return new double3x3(left.c0 + right.c0, left.c1 + right.c1, left.c2 + right.c2);
        }

        public static double3x3 operator -(double3x3 left, double3x3 right)
        {
            return new double3x3(left.c0 - right.c0, left.c1 - right.c1, left.c2 - right.c2);
        }

        public static double3x3 operator -(double3x3 value)
        {
            return new double3x3(-value.c0, -value.c1, -value.c2);
        }

        public static double3x3 operator *(double3x3 left, double right)
        {
            return new double3x3(left.c0 * right, left.c1 * right, left.c2 * right);
        }

        public static double3x3 operator *(double left, double3x3 right)
        {
            return new double3x3(left * right.c0, left * right.c1, left * right.c2);
        }

        public static double3x3 operator /(double3x3 left, double right)
        {
            return new double3x3(left.c0 / right, left.c1 / right, left.c2 / right);
        }

        public static double3 operator *(double3x3 left, double3 right)
        {
            return new double3(left.c0.x * right.x + left.c1.x * right.y + left.c2.x * right.z, left.c0.y * right.x + left.c1.y * right.y + left.c2.y * right.z, left.c0.z * right.x + left.c1.z * right.y + left.c2.z * right.z);
        }

        public static double3 operator *(double3 left, double3x3 right)
        {
            return new double3(left.x * right.c0.x + left.y * right.c0.y + left.z * right.c0.z, left.x * right.c1.x + left.y * right.c1.y + left.z * right.c1.z, left.x * right.c2.x + left.y * right.c2.y + left.z * right.c2.z);
        }

        public static bool operator ==(double3x3 left, double3x3 right)
        {
            return left.c0 == right.c0 && left.c1 == right.c1 && left.c2 == right.c2;
        }

        public static bool operator !=(double3x3 left, double3x3 right)
        {
            return !(left == right);
        }

        public static double2x3 operator *(double3x3 left, double2x3 right)
        {
            return new double2x3(left * right.c0, left * right.c1);
        }

        public static double3x3 operator *(double3x3 left, double3x3 right)
        {
            return new double3x3(left * right.c0, left * right.c1, left * right.c2);
        }

        public static double4x3 operator *(double3x3 left, double4x3 right)
        {
            return new double4x3(left * right.c0, left * right.c1, left * right.c2, left * right.c3);
        }
    }
}
