// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double4x4
    {

        public static double4x4 Transpose(double4x4 value)
        {
            return new double4x4(new double4(value.c0.x, value.c1.x, value.c2.x, value.c3.x), new double4(value.c0.y, value.c1.y, value.c2.y, value.c3.y), new double4(value.c0.z, value.c1.z, value.c2.z, value.c3.z), new double4(value.c0.w, value.c1.w, value.c2.w, value.c3.w));
        }

        public static double4x4 MatrixCompMult(double4x4 left, double4x4 right)
        {
            return new double4x4(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2, left.c3 * right.c3);
        }

        public static double4x4 OuterProduct(double4 c, double4 r)
        {
            return new double4x4(c * r.x, c * r.y, c * r.z, c * r.w);
        }

        public static double Determinant(double4x4 value)
        {
            static double minor(double a11, double a12, double a13, double a21, double a22, double a23, double a31, double a32, double a33) => a11 * (a22 * a33 - a23 * a32) - a12 * (a21 * a33 - a23 * a31) + a13 * (a21 * a32 - a22 * a31);
            return value.M11 * minor(value.M22, value.M23, value.M24, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44) - value.M12 * minor(value.M21, value.M23, value.M24, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44) + value.M13 * minor(value.M21, value.M22, value.M24, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44) - value.M14 * minor(value.M21, value.M22, value.M23, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43);
        }

        public static bool TryInverse(double4x4 value, out double4x4 result)
        {
            var determinant = Determinant(value);
            if (DeltaMaths.Abs(determinant) <= 1e-12) { result = default; return false; }
            var inverse = 1.0 / determinant;
            static double minor(double a11, double a12, double a13, double a21, double a22, double a23, double a31, double a32, double a33) => a11 * (a22 * a33 - a23 * a32) - a12 * (a21 * a33 - a23 * a31) + a13 * (a21 * a32 - a22 * a31);
            result = new double4x4(
                minor(value.M22, value.M23, value.M24, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44) * inverse,
                -minor(value.M12, value.M13, value.M14, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44) * inverse,
                minor(value.M12, value.M13, value.M14, value.M22, value.M23, value.M24, value.M42, value.M43, value.M44) * inverse,
                -minor(value.M12, value.M13, value.M14, value.M22, value.M23, value.M24, value.M32, value.M33, value.M34) * inverse,
                -minor(value.M21, value.M23, value.M24, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44) * inverse,
                minor(value.M11, value.M13, value.M14, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44) * inverse,
                -minor(value.M11, value.M13, value.M14, value.M21, value.M23, value.M24, value.M41, value.M43, value.M44) * inverse,
                minor(value.M11, value.M13, value.M14, value.M21, value.M23, value.M24, value.M31, value.M33, value.M34) * inverse,
                minor(value.M21, value.M22, value.M24, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44) * inverse,
                -minor(value.M11, value.M12, value.M14, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44) * inverse,
                minor(value.M11, value.M12, value.M14, value.M21, value.M22, value.M24, value.M41, value.M42, value.M44) * inverse,
                -minor(value.M11, value.M12, value.M14, value.M21, value.M22, value.M24, value.M31, value.M32, value.M34) * inverse,
                -minor(value.M21, value.M22, value.M23, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43) * inverse,
                minor(value.M11, value.M12, value.M13, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43) * inverse,
                -minor(value.M11, value.M12, value.M13, value.M21, value.M22, value.M23, value.M41, value.M42, value.M43) * inverse,
                minor(value.M11, value.M12, value.M13, value.M21, value.M22, value.M23, value.M31, value.M32, value.M33) * inverse);
            return true;
        }

        public static double4x4 Inverse(double4x4 value)
        {
            return TryInverse(value, out var result) ? result : double4x4.identity;
        }
    }
}
