// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double4x2
    {

        public static double2x4 Transpose(double4x2 value)
        {
            return new double2x4(new double4(value.c0.x, value.c1.x, value.c2.x, value.c3.x), new double4(value.c0.y, value.c1.y, value.c2.y, value.c3.y));
        }

        public static double4x2 MatrixCompMult(double4x2 left, double4x2 right)
        {
            return new double4x2(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2, left.c3 * right.c3);
        }

        public static double4x2 OuterProduct(double2 c, double4 r)
        {
            return new double4x2(c * r.x, c * r.y, c * r.z, c * r.w);
        }
    }
}
