// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double2x2
    {

        public static double2x2 operator +(double2x2 left, double2x2 right)
        {
            return new double2x2(left.c0 + right.c0, left.c1 + right.c1);
        }

        public static double2x2 operator -(double2x2 left, double2x2 right)
        {
            return new double2x2(left.c0 - right.c0, left.c1 - right.c1);
        }

        public static double2x2 operator -(double2x2 value)
        {
            return new double2x2(-value.c0, -value.c1);
        }

        public static double2x2 operator *(double2x2 left, double right)
        {
            return new double2x2(left.c0 * right, left.c1 * right);
        }

        public static double2x2 operator *(double left, double2x2 right)
        {
            return new double2x2(left * right.c0, left * right.c1);
        }

        public static double2x2 operator /(double2x2 left, double right)
        {
            return new double2x2(left.c0 / right, left.c1 / right);
        }

        public static double2 operator *(double2x2 left, double2 right)
        {
            return new double2(left.c0.x * right.x + left.c1.x * right.y, left.c0.y * right.x + left.c1.y * right.y);
        }

        public static double2 operator *(double2 left, double2x2 right)
        {
            return new double2(left.x * right.c0.x + left.y * right.c0.y, left.x * right.c1.x + left.y * right.c1.y);
        }

        public static bool operator ==(double2x2 left, double2x2 right)
        {
            return left.c0 == right.c0 && left.c1 == right.c1;
        }

        public static bool operator !=(double2x2 left, double2x2 right)
        {
            return !(left == right);
        }

        public static double2x2 operator *(double2x2 left, double2x2 right)
        {
            return new double2x2(left * right.c0, left * right.c1);
        }

        public static double3x2 operator *(double2x2 left, double3x2 right)
        {
            return new double3x2(left * right.c0, left * right.c1, left * right.c2);
        }

        public static double4x2 operator *(double2x2 left, double4x2 right)
        {
            return new double4x2(left * right.c0, left * right.c1, left * right.c2, left * right.c3);
        }
    }
}
