// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3x2
    {

        public static double2x3 Transpose(double3x2 value)
        {
            return new double2x3(new double3(value.c0.x, value.c1.x, value.c2.x), new double3(value.c0.y, value.c1.y, value.c2.y));
        }

        public static double3x2 MatrixCompMult(double3x2 left, double3x2 right)
        {
            return new double3x2(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2);
        }

        public static double3x2 OuterProduct(double2 c, double3 r)
        {
            return new double3x2(c * r.x, c * r.y, c * r.z);
        }
    }
}
