// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double2x2
    {

        public static double2x2 Transpose(double2x2 value)
        {
            return new double2x2(new double2(value.c0.x, value.c1.x), new double2(value.c0.y, value.c1.y));
        }

        public static double2x2 MatrixCompMult(double2x2 left, double2x2 right)
        {
            return new double2x2(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static double2x2 OuterProduct(double2 c, double2 r)
        {
            return new double2x2(c * r.x, c * r.y);
        }

        public static double Determinant(double2x2 value)
        {
            return value.M11 * value.M22 - value.M12 * value.M21;
        }

        public static bool TryInverse(double2x2 value, out double2x2 result)
        {
            var determinant = Determinant(value);
            if (DeltaMaths.Abs(determinant) <= 1e-12) { result = default; return false; }
            var inverse = 1.0 / determinant;
            result = new double2x2(value.M22 * inverse, -value.M12 * inverse, -value.M21 * inverse, value.M11 * inverse);
            return true;
        }

        public static double2x2 Inverse(double2x2 value)
        {
            return TryInverse(value, out var result) ? result : double2x2.identity;
        }
    }
}
