// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3x4
    {

        public static double4x3 Transpose(double3x4 value)
        {
            return new double4x3(new double3(value.c0.x, value.c1.x, value.c2.x), new double3(value.c0.y, value.c1.y, value.c2.y), new double3(value.c0.z, value.c1.z, value.c2.z), new double3(value.c0.w, value.c1.w, value.c2.w));
        }

        public static double3x4 MatrixCompMult(double3x4 left, double3x4 right)
        {
            return new double3x4(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2);
        }

        public static double3x4 OuterProduct(double4 c, double3 r)
        {
            return new double3x4(c * r.x, c * r.y, c * r.z);
        }
    }
}
