// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double2x4
    {

        public static double4x2 Transpose(double2x4 value)
        {
            return new double4x2(new double2(value.c0.x, value.c1.x), new double2(value.c0.y, value.c1.y), new double2(value.c0.z, value.c1.z), new double2(value.c0.w, value.c1.w));
        }

        public static double2x4 MatrixCompMult(double2x4 left, double2x4 right)
        {
            return new double2x4(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static double2x4 OuterProduct(double4 c, double2 r)
        {
            return new double2x4(c * r.x, c * r.y);
        }
    }
}
