// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct double2x3
    {

        public static double3x2 Transpose(double2x3 value)
        {
            return new double3x2(new double2(value.c0.x, value.c1.x), new double2(value.c0.y, value.c1.y), new double2(value.c0.z, value.c1.z));
        }

        public static double2x3 MatrixCompMult(double2x3 left, double2x3 right)
        {
            return new double2x3(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static double2x3 OuterProduct(double3 c, double2 r)
        {
            return new double2x3(c * r.x, c * r.y);
        }
    }
}
