// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    /// <summary>A column-major 3x4 matrix represented by 3 double4 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct double3x4 : IEquatable<double3x4>
    {

        /// <summary>Column 0.</summary>
        public double4 c0;

        /// <summary>Column 1.</summary>
        public double4 c1;

        /// <summary>Column 2.</summary>
        public double4 c2;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly double3x4 zero = new double3x4(double4.zero, double4.zero, double4.zero);

        /// <summary>Creates a matrix from its columns in column-major order.</summary>
        public double3x4(double4 c0, double4 c1, double4 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        /// <summary>Creates a matrix with value on the diagonal and zero elsewhere.</summary>
        public double3x4(double value)
        {
            c0 = new double4(value, 0.0, 0.0, 0.0);
            c1 = new double4(0.0, value, 0.0, 0.0);
            c2 = new double4(0.0, 0.0, value, 0.0);
        }

        /// <summary>Creates a matrix from row-major named components in mathematical order.</summary>
        public double3x4(double m11, double m12, double m13, double m21, double m22, double m23, double m31, double m32, double m33, double m41, double m42, double m43)
        {
            c0 = new double4(m11, m21, m31, m41);
            c1 = new double4(m12, m22, m32, m42);
            c2 = new double4(m13, m23, m33, m43);
        }

        /// <summary>Creates a double3x4 from a float2x2 using GLSL matrix conversion rules.</summary>
        public double3x4(float2x2 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, 0.0, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, 0.0, 0.0);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a float2x3 using GLSL matrix conversion rules.</summary>
        public double3x4(float2x3 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, 0.0);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a float2x4 using GLSL matrix conversion rules.</summary>
        public double3x4(float2x4 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, (double)value.c0.w);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, (double)value.c1.w);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a float3x2 using GLSL matrix conversion rules.</summary>
        public double3x4(float3x2 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, 0.0, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, 0.0, 0.0);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a float3x3 using GLSL matrix conversion rules.</summary>
        public double3x4(float3x3 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, 0.0);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, (double)value.c2.z, 0.0);
        }

        /// <summary>Creates a double3x4 from a float3x4 using GLSL matrix conversion rules.</summary>
        public double3x4(float3x4 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, (double)value.c0.w);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, (double)value.c1.w);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, (double)value.c2.z, (double)value.c2.w);
        }

        /// <summary>Creates a double3x4 from a float4x2 using GLSL matrix conversion rules.</summary>
        public double3x4(float4x2 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, 0.0, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, 0.0, 0.0);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a float4x3 using GLSL matrix conversion rules.</summary>
        public double3x4(float4x3 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, 0.0);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, 0.0);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, (double)value.c2.z, 0.0);
        }

        /// <summary>Creates a double3x4 from a float4x4 using GLSL matrix conversion rules.</summary>
        public double3x4(float4x4 value)
        {
            c0 = new double4((double)value.c0.x, (double)value.c0.y, (double)value.c0.z, (double)value.c0.w);
            c1 = new double4((double)value.c1.x, (double)value.c1.y, (double)value.c1.z, (double)value.c1.w);
            c2 = new double4((double)value.c2.x, (double)value.c2.y, (double)value.c2.z, (double)value.c2.w);
        }

        /// <summary>Creates a double3x4 from a double2x2 using GLSL matrix conversion rules.</summary>
        public double3x4(double2x2 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, 0.0, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, 0.0, 0.0);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a double2x3 using GLSL matrix conversion rules.</summary>
        public double3x4(double2x3 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, 0.0);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a double2x4 using GLSL matrix conversion rules.</summary>
        public double3x4(double2x4 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
            c2 = new double4(0.0, 0.0, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a double3x2 using GLSL matrix conversion rules.</summary>
        public double3x4(double3x2 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, 0.0, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, 0.0, 0.0);
            c2 = new double4(value.c2.x, value.c2.y, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a double3x3 using GLSL matrix conversion rules.</summary>
        public double3x4(double3x3 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, 0.0);
            c2 = new double4(value.c2.x, value.c2.y, value.c2.z, 0.0);
        }

        /// <summary>Creates a double3x4 from a double3x4 using GLSL matrix conversion rules.</summary>
        public double3x4(double3x4 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
            c2 = new double4(value.c2.x, value.c2.y, value.c2.z, value.c2.w);
        }

        /// <summary>Creates a double3x4 from a double4x2 using GLSL matrix conversion rules.</summary>
        public double3x4(double4x2 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, 0.0, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, 0.0, 0.0);
            c2 = new double4(value.c2.x, value.c2.y, 1.0, 0.0);
        }

        /// <summary>Creates a double3x4 from a double4x3 using GLSL matrix conversion rules.</summary>
        public double3x4(double4x3 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, 0.0);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, 0.0);
            c2 = new double4(value.c2.x, value.c2.y, value.c2.z, 0.0);
        }

        /// <summary>Creates a double3x4 from a double4x4 using GLSL matrix conversion rules.</summary>
        public double3x4(double4x4 value)
        {
            c0 = new double4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new double4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
            c2 = new double4(value.c2.x, value.c2.y, value.c2.z, value.c2.w);
        }

        /// <summary>Returns a column using zero-based indexing.</summary>
        public double4 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, 2 => c2, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public double3 GetRow(int index)
        {
            return index switch { 0 => new double3(c0.x, c1.x, c2.x), 1 => new double3(c0.y, c1.y, c2.y), 2 => new double3(c0.z, c1.z, c2.z), 3 => new double3(c0.w, c1.w, c2.w), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public double GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, double value)
        {
            if ((uint)column >= 3u || (uint)row >= 4u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; case 2: c2 = columnValue; break; }
        }

        public double M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public double M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public double M13
        {
            get => c2.x;
            set => c2.x = value;
        }

        public double M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public double M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public double M23
        {
            get => c2.y;
            set => c2.y = value;
        }

        public double M31
        {
            get => c0.z;
            set => c0.z = value;
        }

        public double M32
        {
            get => c1.z;
            set => c1.z = value;
        }

        public double M33
        {
            get => c2.z;
            set => c2.z = value;
        }

        public double M41
        {
            get => c0.w;
            set => c0.w = value;
        }

        public double M42
        {
            get => c1.w;
            set => c1.w = value;
        }

        public double M43
        {
            get => c2.w;
            set => c2.w = value;
        }

        public bool Equals(double3x4 other)
        {
            return c0 == other.c0 && c1 == other.c1 && c2 == other.c2;
        }

        public override bool Equals(object? obj)
        {
            return obj is double3x4 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); hash = hash * 31 + c2.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}, {M13}; {M21}, {M22}, {M23}; {M31}, {M32}, {M33}; {M41}, {M42}, {M43}]");
        }
    }
}
