// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double2x4
    {

        public static double2x4 operator +(double2x4 left, double2x4 right)
        {
            return new double2x4(left.c0 + right.c0, left.c1 + right.c1);
        }

        public static double2x4 operator -(double2x4 left, double2x4 right)
        {
            return new double2x4(left.c0 - right.c0, left.c1 - right.c1);
        }

        public static double2x4 operator -(double2x4 value)
        {
            return new double2x4(-value.c0, -value.c1);
        }

        public static double2x4 operator *(double2x4 left, double right)
        {
            return new double2x4(left.c0 * right, left.c1 * right);
        }

        public static double2x4 operator *(double left, double2x4 right)
        {
            return new double2x4(left * right.c0, left * right.c1);
        }

        public static double2x4 operator /(double2x4 left, double right)
        {
            return new double2x4(left.c0 / right, left.c1 / right);
        }

        public static double4 operator *(double2x4 left, double2 right)
        {
            return new double4(left.c0.x * right.x + left.c1.x * right.y, left.c0.y * right.x + left.c1.y * right.y, left.c0.z * right.x + left.c1.z * right.y, left.c0.w * right.x + left.c1.w * right.y);
        }

        public static double2 operator *(double4 left, double2x4 right)
        {
            return new double2(left.x * right.c0.x + left.y * right.c0.y + left.z * right.c0.z + left.w * right.c0.w, left.x * right.c1.x + left.y * right.c1.y + left.z * right.c1.z + left.w * right.c1.w);
        }

        public static bool operator ==(double2x4 left, double2x4 right)
        {
            return left.c0 == right.c0 && left.c1 == right.c1;
        }

        public static bool operator !=(double2x4 left, double2x4 right)
        {
            return !(left == right);
        }

        public static double2x4 operator *(double2x4 left, double2x2 right)
        {
            return new double2x4(left * right.c0, left * right.c1);
        }

        public static double3x4 operator *(double2x4 left, double3x2 right)
        {
            return new double3x4(left * right.c0, left * right.c1, left * right.c2);
        }

        public static double4x4 operator *(double2x4 left, double4x2 right)
        {
            return new double4x4(left * right.c0, left * right.c1, left * right.c2, left * right.c3);
        }
    }
}
