// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct fix3
    {

        public static fix3 Sqrt(fix3 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y), DeltaMaths.Sqrt(value.z));
        }

        public static fix3 InverseSqrt(fix3 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y), DeltaMaths.InverseSqrt(value.z));
        }
    }
}
