// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct fix4
    {

        public static fix4 Sin(fix4 value)
        {
            return new(DeltaMaths.Sin(value.x), DeltaMaths.Sin(value.y), DeltaMaths.Sin(value.z), DeltaMaths.Sin(value.w));
        }

        public static fix4 Cos(fix4 value)
        {
            return new(DeltaMaths.Cos(value.x), DeltaMaths.Cos(value.y), DeltaMaths.Cos(value.z), DeltaMaths.Cos(value.w));
        }

        public static fix4 Tan(fix4 value)
        {
            return new(DeltaMaths.Tan(value.x), DeltaMaths.Tan(value.y), DeltaMaths.Tan(value.z), DeltaMaths.Tan(value.w));
        }

        public static fix4 Asin(fix4 value)
        {
            return new(DeltaMaths.Asin(value.x), DeltaMaths.Asin(value.y), DeltaMaths.Asin(value.z), DeltaMaths.Asin(value.w));
        }

        public static fix4 Acos(fix4 value)
        {
            return new(DeltaMaths.Acos(value.x), DeltaMaths.Acos(value.y), DeltaMaths.Acos(value.z), DeltaMaths.Acos(value.w));
        }

        public static fix4 Atan(fix4 value)
        {
            return new(DeltaMaths.Atan(value.x), DeltaMaths.Atan(value.y), DeltaMaths.Atan(value.z), DeltaMaths.Atan(value.w));
        }

        public static fix4 Atan2(fix4 y, fix4 x)
        {
            return new(DeltaMaths.Atan2(y.x, x.x), DeltaMaths.Atan2(y.y, x.y), DeltaMaths.Atan2(y.z, x.z), DeltaMaths.Atan2(y.w, x.w));
        }

        public static fix4 Atan2(fix4 y, fix x)
        {
            return new(DeltaMaths.Atan2(y.x, x), DeltaMaths.Atan2(y.y, x), DeltaMaths.Atan2(y.z, x), DeltaMaths.Atan2(y.w, x));
        }

        public static fix4 Atan2(fix y, fix4 x)
        {
            return new(DeltaMaths.Atan2(y, x.x), DeltaMaths.Atan2(y, x.y), DeltaMaths.Atan2(y, x.z), DeltaMaths.Atan2(y, x.w));
        }
    }
}
