// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A column-major 2x4 matrix represented by 2 float4 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct float2x4 : IEquatable<float2x4>
    {

        /// <summary>Column 0.</summary>
        public float4 c0;

        /// <summary>Column 1.</summary>
        public float4 c1;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly float2x4 zero = new float2x4(float4.zero, float4.zero);

        /// <summary>Creates a matrix from its columns in column-major order.</summary>
        public float2x4(float4 c0, float4 c1)
        {
            this.c0 = c0;
            this.c1 = c1;
        }

        /// <summary>Creates a matrix with value on the diagonal and zero elsewhere.</summary>
        public float2x4(float value)
        {
            c0 = new float4(value, 0f, 0f, 0f);
            c1 = new float4(0f, value, 0f, 0f);
        }

        /// <summary>Creates a matrix from row-major named components in mathematical order.</summary>
        public float2x4(float m11, float m12, float m21, float m22, float m31, float m32, float m41, float m42)
        {
            c0 = new float4(m11, m21, m31, m41);
            c1 = new float4(m12, m22, m32, m42);
        }

        /// <summary>Creates a float2x4 from a float2x2 using GLSL matrix conversion rules.</summary>
        public float2x4(float2x2 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, 0f, 0f);
            c1 = new float4(value.c1.x, value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a float2x3 using GLSL matrix conversion rules.</summary>
        public float2x4(float2x3 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, 0f);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a float2x4 using GLSL matrix conversion rules.</summary>
        public float2x4(float2x4 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
        }

        /// <summary>Creates a float2x4 from a float3x2 using GLSL matrix conversion rules.</summary>
        public float2x4(float3x2 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, 0f, 0f);
            c1 = new float4(value.c1.x, value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a float3x3 using GLSL matrix conversion rules.</summary>
        public float2x4(float3x3 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, 0f);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a float3x4 using GLSL matrix conversion rules.</summary>
        public float2x4(float3x4 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
        }

        /// <summary>Creates a float2x4 from a float4x2 using GLSL matrix conversion rules.</summary>
        public float2x4(float4x2 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, 0f, 0f);
            c1 = new float4(value.c1.x, value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a float4x3 using GLSL matrix conversion rules.</summary>
        public float2x4(float4x3 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, 0f);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a float4x4 using GLSL matrix conversion rules.</summary>
        public float2x4(float4x4 value)
        {
            c0 = new float4(value.c0.x, value.c0.y, value.c0.z, value.c0.w);
            c1 = new float4(value.c1.x, value.c1.y, value.c1.z, value.c1.w);
        }

        /// <summary>Creates a float2x4 from a double2x2 using GLSL matrix conversion rules.</summary>
        public float2x4(double2x2 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, 0f, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a double2x3 using GLSL matrix conversion rules.</summary>
        public float2x4(double2x3 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a double2x4 using GLSL matrix conversion rules.</summary>
        public float2x4(double2x4 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, (float)value.c0.w);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, (float)value.c1.w);
        }

        /// <summary>Creates a float2x4 from a double3x2 using GLSL matrix conversion rules.</summary>
        public float2x4(double3x2 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, 0f, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a double3x3 using GLSL matrix conversion rules.</summary>
        public float2x4(double3x3 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a double3x4 using GLSL matrix conversion rules.</summary>
        public float2x4(double3x4 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, (float)value.c0.w);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, (float)value.c1.w);
        }

        /// <summary>Creates a float2x4 from a double4x2 using GLSL matrix conversion rules.</summary>
        public float2x4(double4x2 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, 0f, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, 0f, 0f);
        }

        /// <summary>Creates a float2x4 from a double4x3 using GLSL matrix conversion rules.</summary>
        public float2x4(double4x3 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, 0f);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, 0f);
        }

        /// <summary>Creates a float2x4 from a double4x4 using GLSL matrix conversion rules.</summary>
        public float2x4(double4x4 value)
        {
            c0 = new float4((float)value.c0.x, (float)value.c0.y, (float)value.c0.z, (float)value.c0.w);
            c1 = new float4((float)value.c1.x, (float)value.c1.y, (float)value.c1.z, (float)value.c1.w);
        }

        /// <summary>Returns a column using zero-based indexing.</summary>
        public float4 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public float2 GetRow(int index)
        {
            return index switch { 0 => new float2(c0.x, c1.x), 1 => new float2(c0.y, c1.y), 2 => new float2(c0.z, c1.z), 3 => new float2(c0.w, c1.w), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public float GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, float value)
        {
            if ((uint)column >= 2u || (uint)row >= 4u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; }
        }

        public float M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public float M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public float M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public float M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public float M31
        {
            get => c0.z;
            set => c0.z = value;
        }

        public float M32
        {
            get => c1.z;
            set => c1.z = value;
        }

        public float M41
        {
            get => c0.w;
            set => c0.w = value;
        }

        public float M42
        {
            get => c1.w;
            set => c1.w = value;
        }

        public bool Equals(float2x4 other)
        {
            return c0 == other.c0 && c1 == other.c1;
        }

        public override bool Equals(object? obj)
        {
            return obj is float2x4 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}; {M21}, {M22}; {M31}, {M32}; {M41}, {M42}]");
        }
    }
}
