// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A column-major 3x3 matrix represented by 3 float3 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct float3x3 : IEquatable<float3x3>
    {

        /// <summary>Column 0.</summary>
        public float3 c0;

        private float _padding0;

        /// <summary>Column 1.</summary>
        public float3 c1;

        private float _padding1;

        /// <summary>Column 2.</summary>
        public float3 c2;

        private float _padding2;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly float3x3 zero = new float3x3(float3.zero, float3.zero, float3.zero);

        /// <summary>The identity matrix.</summary>
        public static readonly float3x3 identity = new float3x3(1f);

        /// <summary>Creates a matrix from its columns in column-major order.</summary>
        public float3x3(float3 c0, float3 c1, float3 c2)
        {
            this.c0 = c0;
            this._padding0 = 0f;
            this.c1 = c1;
            this._padding1 = 0f;
            this.c2 = c2;
            this._padding2 = 0f;
        }

        /// <summary>Creates a matrix with value on the diagonal and zero elsewhere.</summary>
        public float3x3(float value)
        {
            c0 = new float3(value, 0f, 0f);
            _padding0 = 0f;
            c1 = new float3(0f, value, 0f);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, value);
            _padding2 = 0f;
        }

        /// <summary>Creates a matrix from row-major named components in mathematical order.</summary>
        public float3x3(float m11, float m12, float m13, float m21, float m22, float m23, float m31, float m32, float m33)
        {
            c0 = new float3(m11, m21, m31);
            _padding0 = 0f;
            c1 = new float3(m12, m22, m32);
            _padding1 = 0f;
            c2 = new float3(m13, m23, m33);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float2x2 using GLSL matrix conversion rules.</summary>
        public float3x3(float2x2 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float2x3 using GLSL matrix conversion rules.</summary>
        public float3x3(float2x3 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float2x4 using GLSL matrix conversion rules.</summary>
        public float3x3(float2x4 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float3x2 using GLSL matrix conversion rules.</summary>
        public float3x3(float3x2 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float3x3 using GLSL matrix conversion rules.</summary>
        public float3x3(float3x3 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float3x4 using GLSL matrix conversion rules.</summary>
        public float3x3(float3x4 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float4x2 using GLSL matrix conversion rules.</summary>
        public float3x3(float4x2 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float4x3 using GLSL matrix conversion rules.</summary>
        public float3x3(float4x3 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a float4x4 using GLSL matrix conversion rules.</summary>
        public float3x3(float4x4 value)
        {
            c0 = new float3(value.c0.x, value.c0.y, value.c0.z);
            _padding0 = 0f;
            c1 = new float3(value.c1.x, value.c1.y, value.c1.z);
            _padding1 = 0f;
            c2 = new float3(value.c2.x, value.c2.y, value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double2x2 using GLSL matrix conversion rules.</summary>
        public float3x3(double2x2 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double2x3 using GLSL matrix conversion rules.</summary>
        public float3x3(double2x3 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double2x4 using GLSL matrix conversion rules.</summary>
        public float3x3(double2x4 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3(0f, 0f, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double3x2 using GLSL matrix conversion rules.</summary>
        public float3x3(double3x2 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double3x3 using GLSL matrix conversion rules.</summary>
        public float3x3(double3x3 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, (float)value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double3x4 using GLSL matrix conversion rules.</summary>
        public float3x3(double3x4 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, (float)value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double4x2 using GLSL matrix conversion rules.</summary>
        public float3x3(double4x2 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, 0f);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, 0f);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, 1f);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double4x3 using GLSL matrix conversion rules.</summary>
        public float3x3(double4x3 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, (float)value.c2.z);
            _padding2 = 0f;
        }

        /// <summary>Creates a float3x3 from a double4x4 using GLSL matrix conversion rules.</summary>
        public float3x3(double4x4 value)
        {
            c0 = new float3((float)value.c0.x, (float)value.c0.y, (float)value.c0.z);
            _padding0 = 0f;
            c1 = new float3((float)value.c1.x, (float)value.c1.y, (float)value.c1.z);
            _padding1 = 0f;
            c2 = new float3((float)value.c2.x, (float)value.c2.y, (float)value.c2.z);
            _padding2 = 0f;
        }

        public static float3x3 Identity => identity;

        /// <summary>Returns a column using zero-based indexing.</summary>
        public float3 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, 2 => c2, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public float3 GetRow(int index)
        {
            return index switch { 0 => new float3(c0.x, c1.x, c2.x), 1 => new float3(c0.y, c1.y, c2.y), 2 => new float3(c0.z, c1.z, c2.z), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public float GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, float value)
        {
            if ((uint)column >= 3u || (uint)row >= 3u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; case 2: c2 = columnValue; break; }
        }

        public float M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public float M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public float M13
        {
            get => c2.x;
            set => c2.x = value;
        }

        public float M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public float M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public float M23
        {
            get => c2.y;
            set => c2.y = value;
        }

        public float M31
        {
            get => c0.z;
            set => c0.z = value;
        }

        public float M32
        {
            get => c1.z;
            set => c1.z = value;
        }

        public float M33
        {
            get => c2.z;
            set => c2.z = value;
        }

        public bool Equals(float3x3 other)
        {
            return c0 == other.c0 && c1 == other.c1 && c2 == other.c2;
        }

        public override bool Equals(object? obj)
        {
            return obj is float3x3 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); hash = hash * 31 + c2.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}, {M13}; {M21}, {M22}, {M23}; {M31}, {M32}, {M33}]");
        }
    }
}
