// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float2
    {

        public static float2 Exp(float2 value)
        {
            return new(DeltaMaths.Exp(value.x), DeltaMaths.Exp(value.y));
        }

        public static float2 Exp2(float2 value)
        {
            return new(DeltaMaths.Exp2(value.x), DeltaMaths.Exp2(value.y));
        }

        public static float2 Log(float2 value)
        {
            return new(DeltaMaths.Log(value.x), DeltaMaths.Log(value.y));
        }

        public static float2 Log2(float2 value)
        {
            return new(DeltaMaths.Log2(value.x), DeltaMaths.Log2(value.y));
        }

        public static float2 Log10(float2 value)
        {
            return new(DeltaMaths.Log10(value.x), DeltaMaths.Log10(value.y));
        }

        public static float2 Sqrt(float2 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y));
        }

        public static float2 InverseSqrt(float2 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y));
        }

        public static float2 Cbrt(float2 value)
        {
            return new(DeltaMaths.Cbrt(value.x), DeltaMaths.Cbrt(value.y));
        }

        public static float2 Pow(float2 a, float2 b)
        {
            return new(DeltaMaths.Pow(a.x, b.x), DeltaMaths.Pow(a.y, b.y));
        }

        public static float2 Pow(float2 a, float b)
        {
            return new(DeltaMaths.Pow(a.x, b), DeltaMaths.Pow(a.y, b));
        }

        public static float2 Pow(float a, float2 b)
        {
            return new(DeltaMaths.Pow(a, b.x), DeltaMaths.Pow(a, b.y));
        }
    }
}
