// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float2x3
    {

        public static float3x2 Transpose(float2x3 value)
        {
            return new float3x2(new float2(value.c0.x, value.c1.x), new float2(value.c0.y, value.c1.y), new float2(value.c0.z, value.c1.z));
        }

        public static float2x3 MatrixCompMult(float2x3 left, float2x3 right)
        {
            return new float2x3(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static float2x3 OuterProduct(float3 c, float2 r)
        {
            return new float2x3(c * r.x, c * r.y);
        }
    }
}
