// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A column-major 4x2 matrix represented by 4 float2 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct float4x2 : IEquatable<float4x2>
    {

        /// <summary>Column 0.</summary>
        public float2 c0;

        /// <summary>Column 1.</summary>
        public float2 c1;

        /// <summary>Column 2.</summary>
        public float2 c2;

        /// <summary>Column 3.</summary>
        public float2 c3;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly float4x2 zero = new float4x2(float2.zero, float2.zero, float2.zero, float2.zero);

        /// <summary>Creates a matrix from its columns in column-major order.</summary>
        public float4x2(float2 c0, float2 c1, float2 c2, float2 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        /// <summary>Creates a matrix with value on the diagonal and zero elsewhere.</summary>
        public float4x2(float value)
        {
            c0 = new float2(value, 0f);
            c1 = new float2(0f, value);
            c2 = new float2(0f, 0f);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a matrix from row-major named components in mathematical order.</summary>
        public float4x2(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24)
        {
            c0 = new float2(m11, m21);
            c1 = new float2(m12, m22);
            c2 = new float2(m13, m23);
            c3 = new float2(m14, m24);
        }

        /// <summary>Creates a float4x2 from a float2x2 using GLSL matrix conversion rules.</summary>
        public float4x2(float2x2 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(0f, 0f);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float2x3 using GLSL matrix conversion rules.</summary>
        public float4x2(float2x3 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(0f, 0f);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float2x4 using GLSL matrix conversion rules.</summary>
        public float4x2(float2x4 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(0f, 0f);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float3x2 using GLSL matrix conversion rules.</summary>
        public float4x2(float3x2 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float3x3 using GLSL matrix conversion rules.</summary>
        public float4x2(float3x3 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float3x4 using GLSL matrix conversion rules.</summary>
        public float4x2(float3x4 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(0f, 0f);
        }

        /// <summary>Creates a float4x2 from a float4x2 using GLSL matrix conversion rules.</summary>
        public float4x2(float4x2 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(value.c3.x, value.c3.y);
        }

        /// <summary>Creates a float4x2 from a float4x3 using GLSL matrix conversion rules.</summary>
        public float4x2(float4x3 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(value.c3.x, value.c3.y);
        }

        /// <summary>Creates a float4x2 from a float4x4 using GLSL matrix conversion rules.</summary>
        public float4x2(float4x4 value)
        {
            c0 = new float2(value.c0.x, value.c0.y);
            c1 = new float2(value.c1.x, value.c1.y);
            c2 = new float2(value.c2.x, value.c2.y);
            c3 = new float2(value.c3.x, value.c3.y);
        }

        /// <summary>Returns a column using zero-based indexing.</summary>
        public float2 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, 2 => c2, 3 => c3, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public float4 GetRow(int index)
        {
            return index switch { 0 => new float4(c0.x, c1.x, c2.x, c3.x), 1 => new float4(c0.y, c1.y, c2.y, c3.y), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public float GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, float value)
        {
            if ((uint)column >= 4u || (uint)row >= 2u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; case 2: c2 = columnValue; break; case 3: c3 = columnValue; break; }
        }

        public float M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public float M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public float M13
        {
            get => c2.x;
            set => c2.x = value;
        }

        public float M14
        {
            get => c3.x;
            set => c3.x = value;
        }

        public float M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public float M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public float M23
        {
            get => c2.y;
            set => c2.y = value;
        }

        public float M24
        {
            get => c3.y;
            set => c3.y = value;
        }

        public bool Equals(float4x2 other)
        {
            return c0 == other.c0 && c1 == other.c1 && c2 == other.c2 && c3 == other.c3;
        }

        public override bool Equals(object? obj)
        {
            return obj is float4x2 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); hash = hash * 31 + c2.GetHashCode(); hash = hash * 31 + c3.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}, {M13}, {M14}; {M21}, {M22}, {M23}, {M24}]");
        }
    }
}
