// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct float3x4
    {

        public static float4x3 Transpose(float3x4 value)
        {
            return new float4x3(new float3(value.c0.x, value.c1.x, value.c2.x), new float3(value.c0.y, value.c1.y, value.c2.y), new float3(value.c0.z, value.c1.z, value.c2.z), new float3(value.c0.w, value.c1.w, value.c2.w));
        }

        public static float3x4 MatrixCompMult(float3x4 left, float3x4 right)
        {
            return new float3x4(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2);
        }

        public static float3x4 OuterProduct(float4 c, float3 r)
        {
            return new float3x4(c * r.x, c * r.y, c * r.z);
        }
    }
}
