// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float2x4
    {

        public static float4x2 Transpose(float2x4 value)
        {
            return new float4x2(new float2(value.c0.x, value.c1.x), new float2(value.c0.y, value.c1.y), new float2(value.c0.z, value.c1.z), new float2(value.c0.w, value.c1.w));
        }

        public static float2x4 MatrixCompMult(float2x4 left, float2x4 right)
        {
            return new float2x4(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static float2x4 OuterProduct(float4 c, float2 r)
        {
            return new float2x4(c * r.x, c * r.y);
        }
    }
}
