// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct float3x3
    {

        public static float3x3 Transpose(float3x3 value)
        {
            return new float3x3(new float3(value.c0.x, value.c1.x, value.c2.x), new float3(value.c0.y, value.c1.y, value.c2.y), new float3(value.c0.z, value.c1.z, value.c2.z));
        }

        public static float3x3 MatrixCompMult(float3x3 left, float3x3 right)
        {
            return new float3x3(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2);
        }

        public static float3x3 OuterProduct(float3 c, float3 r)
        {
            return new float3x3(c * r.x, c * r.y, c * r.z);
        }

        public static float Determinant(float3x3 value)
        {
            return value.M11 * (value.M22 * value.M33 - value.M23 * value.M32) - value.M12 * (value.M21 * value.M33 - value.M23 * value.M31) + value.M13 * (value.M21 * value.M32 - value.M22 * value.M31);
        }

        public static bool TryInverse(float3x3 value, out float3x3 result)
        {
            var c11 = value.M22 * value.M33 - value.M23 * value.M32;
            var c12 = value.M13 * value.M32 - value.M12 * value.M33;
            var c13 = value.M12 * value.M23 - value.M13 * value.M22;
            var c21 = value.M23 * value.M31 - value.M21 * value.M33;
            var c22 = value.M11 * value.M33 - value.M13 * value.M31;
            var c23 = value.M13 * value.M21 - value.M11 * value.M23;
            var c31 = value.M21 * value.M32 - value.M22 * value.M31;
            var c32 = value.M12 * value.M31 - value.M11 * value.M32;
            var c33 = value.M11 * value.M22 - value.M12 * value.M21;
            var determinant = value.M11 * c11 + value.M12 * c12 + value.M13 * c13;
            if (DeltaMaths.Abs(determinant) <= 1e-8f) { result = default; return false; }
            var inverse = 1f / determinant;
            result = new float3x3(c11 * inverse, c21 * inverse, c31 * inverse, c12 * inverse, c22 * inverse, c32 * inverse, c13 * inverse, c23 * inverse, c33 * inverse);
            return true;
        }

        public static float3x3 Inverse(float3x3 value)
        {
            return TryInverse(value, out var result) ? result : float3x3.identity;
        }
    }
}
