// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct float4x3
    {

        public static float3x4 Transpose(float4x3 value)
        {
            return new float3x4(new float4(value.c0.x, value.c1.x, value.c2.x, value.c3.x), new float4(value.c0.y, value.c1.y, value.c2.y, value.c3.y), new float4(value.c0.z, value.c1.z, value.c2.z, value.c3.z));
        }

        public static float4x3 MatrixCompMult(float4x3 left, float4x3 right)
        {
            return new float4x3(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2, left.c3 * right.c3);
        }

        public static float4x3 OuterProduct(float3 c, float4 r)
        {
            return new float4x3(c * r.x, c * r.y, c * r.z, c * r.w);
        }
    }
}
