// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct float2x3
    {

        public static float2x3 operator +(float2x3 left, float2x3 right)
        {
            return new float2x3(left.c0 + right.c0, left.c1 + right.c1);
        }

        public static float2x3 operator -(float2x3 left, float2x3 right)
        {
            return new float2x3(left.c0 - right.c0, left.c1 - right.c1);
        }

        public static float2x3 operator -(float2x3 value)
        {
            return new float2x3(-value.c0, -value.c1);
        }

        public static float2x3 operator *(float2x3 left, float right)
        {
            return new float2x3(left.c0 * right, left.c1 * right);
        }

        public static float2x3 operator *(float left, float2x3 right)
        {
            return new float2x3(left * right.c0, left * right.c1);
        }

        public static float2x3 operator /(float2x3 left, float right)
        {
            return new float2x3(left.c0 / right, left.c1 / right);
        }

        public static float3 operator *(float2x3 left, float2 right)
        {
            return new float3(left.c0.x * right.x + left.c1.x * right.y, left.c0.y * right.x + left.c1.y * right.y, left.c0.z * right.x + left.c1.z * right.y);
        }

        public static float2 operator *(float3 left, float2x3 right)
        {
            return new float2(left.x * right.c0.x + left.y * right.c0.y + left.z * right.c0.z, left.x * right.c1.x + left.y * right.c1.y + left.z * right.c1.z);
        }

        public static bool operator ==(float2x3 left, float2x3 right)
        {
            return left.c0 == right.c0 && left.c1 == right.c1;
        }

        public static bool operator !=(float2x3 left, float2x3 right)
        {
            return !(left == right);
        }

        public static float2x3 operator *(float2x3 left, float2x2 right)
        {
            return new float2x3(left * right.c0, left * right.c1);
        }

        public static float3x3 operator *(float2x3 left, float3x2 right)
        {
            return new float3x3(left * right.c0, left * right.c1, left * right.c2);
        }

        public static float4x3 operator *(float2x3 left, float4x2 right)
        {
            return new float4x3(left * right.c0, left * right.c1, left * right.c2, left * right.c3);
        }
    }
}
