// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float2
    {

        public static float2 Min(float2 a, float2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static float2 Min(float2 a, float b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static float2 Min(float a, float2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static float2 Max(float2 a, float2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static float2 Max(float2 a, float b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static float2 Max(float a, float2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static float2 Clamp(float2 value, float min, float max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static float2 Clamp(float2 value, float2 min, float2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static float2 Abs(float2 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y));
        }

        public static float2 Sign(float2 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y));
        }

        public static float Sum(float2 value)
        {
            return value.x + value.y;
        }

        public static float2 Lerp(float2 a, float2 b, float t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t));
        }

        public static float2 Lerp(float2 a, float2 b, float2 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y));
        }

        public static float2 InvLerp(float2 edge0, float2 edge1, float2 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static float2 InvLerp(float2 edge0, float2 edge1, float value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value));
        }

        public static float2 Smoothstep(float2 edge0, float2 edge1, float2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0.x, edge1.x, value.x), DeltaMaths.Smoothstep(edge0.y, edge1.y, value.y));
        }

        public static float2 Smoothstep(float edge0, float edge1, float2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0, edge1, value.x), DeltaMaths.Smoothstep(edge0, edge1, value.y));
        }

        public static float2 Step(float2 edge, float2 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y));
        }

        public static float2 Step(float edge, float2 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y));
        }

        public static float2 Saturate(float2 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y));
        }

        public static float2 Fma(float2 a, float2 b, float2 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y));
        }

        public static float2 Remap(float2 value, float2 sourceFrom, float2 sourceTo, float2 targetFrom, float2 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static float2 Mod(float2 x, float2 y)
        {
            return new(DeltaMaths.Mod(x.x, y.x), DeltaMaths.Mod(x.y, y.y));
        }

        public static float2 Mod(float2 x, float y)
        {
            return new(DeltaMaths.Mod(x.x, y), DeltaMaths.Mod(x.y, y));
        }

        public static uint PackUnorm2x16(float2 value)
        {
            var x = (uint)DeltaMaths.RoundEven(DeltaMaths.Clamp(value.x, 0f, 1f) * 65535f);
            var y = (uint)DeltaMaths.RoundEven(DeltaMaths.Clamp(value.y, 0f, 1f) * 65535f);
            return x | (y << 16);
        }

        public static float2 UnpackUnorm2x16(uint value)
        {
            return new((value & 0xffffu) / 65535f, ((value >> 16) & 0xffffu) / 65535f);
        }

        public static uint PackSnorm2x16(float2 value)
        {
            var x = unchecked((uint)(ushort)(short)DeltaMaths.RoundEven(DeltaMaths.Clamp(value.x, -1f, 1f) * 32767f));
            var y = unchecked((uint)(ushort)(short)DeltaMaths.RoundEven(DeltaMaths.Clamp(value.y, -1f, 1f) * 32767f));
            return x | (y << 16);
        }

        public static float2 UnpackSnorm2x16(uint value)
        {
            var x = unchecked((short)(value & 0xffffu));
            var y = unchecked((short)(value >> 16));
            return new(
                DeltaMaths.Clamp(x / 32767f, -1f, 1f),
                DeltaMaths.Clamp(y / 32767f, -1f, 1f));
        }

        public static float2 Floor(float2 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y));
        }

        public static float2 Ceil(float2 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y));
        }

        public static float2 Round(float2 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y));
        }

        public static float2 RoundEven(float2 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y));
        }

        public static float2 Truncate(float2 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y));
        }

        public static float2 Fract(float2 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y));
        }

        public static float2 Radians(float2 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y));
        }

        public static float2 Degrees(float2 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y));
        }
    }
}
