// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float3x2
    {

        public static float2x3 Transpose(float3x2 value)
        {
            return new float2x3(new float3(value.c0.x, value.c1.x, value.c2.x), new float3(value.c0.y, value.c1.y, value.c2.y));
        }

        public static float3x2 MatrixCompMult(float3x2 left, float3x2 right)
        {
            return new float3x2(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2);
        }

        public static float3x2 OuterProduct(float2 c, float3 r)
        {
            return new float3x2(c * r.x, c * r.y, c * r.z);
        }
    }
}
