// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float2x2
    {

        public static float2x2 Transpose(float2x2 value)
        {
            return new float2x2(new float2(value.c0.x, value.c1.x), new float2(value.c0.y, value.c1.y));
        }

        public static float2x2 MatrixCompMult(float2x2 left, float2x2 right)
        {
            return new float2x2(left.c0 * right.c0, left.c1 * right.c1);
        }

        public static float2x2 OuterProduct(float2 c, float2 r)
        {
            return new float2x2(c * r.x, c * r.y);
        }

        public static float Determinant(float2x2 value)
        {
            return value.M11 * value.M22 - value.M12 * value.M21;
        }

        public static bool TryInverse(float2x2 value, out float2x2 result)
        {
            var determinant = Determinant(value);
            if (DeltaMaths.Abs(determinant) <= 1e-8f) { result = default; return false; }
            var inverse = 1f / determinant;
            result = new float2x2(value.M22 * inverse, -value.M12 * inverse, -value.M21 * inverse, value.M11 * inverse);
            return true;
        }

        public static float2x2 Inverse(float2x2 value)
        {
            return TryInverse(value, out var result) ? result : float2x2.identity;
        }
    }
}
