// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float4x2
    {

        public static float2x4 Transpose(float4x2 value)
        {
            return new float2x4(new float4(value.c0.x, value.c1.x, value.c2.x, value.c3.x), new float4(value.c0.y, value.c1.y, value.c2.y, value.c3.y));
        }

        public static float4x2 MatrixCompMult(float4x2 left, float4x2 right)
        {
            return new float4x2(left.c0 * right.c0, left.c1 * right.c1, left.c2 * right.c2, left.c3 * right.c3);
        }

        public static float4x2 OuterProduct(float2 c, float4 r)
        {
            return new float4x2(c * r.x, c * r.y, c * r.z, c * r.w);
        }
    }
}
