// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half4
    {

        public static half4 Select(half4 falseValue, half4 trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z, mask.w ? trueValue.w : falseValue.w);
        }

        public static half4 Select(half4 falseValue, half4 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z, mask ? trueValue.w : falseValue.w);
        }

        public static half4 Select(half falseValue, half trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue, mask.w ? trueValue : falseValue);
        }

        public static bool4 Equal(half4 a, half4 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        }

        public static bool4 Equal(half4 a, half b)
        {
            return new(a.x == b, a.y == b, a.z == b, a.w == b);
        }

        public static bool4 Equal(half a, half4 b)
        {
            return new(a == b.x, a == b.y, a == b.z, a == b.w);
        }

        public static bool4 NotEqual(half4 a, half4 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        }

        public static bool4 NotEqual(half4 a, half b)
        {
            return new(a.x != b, a.y != b, a.z != b, a.w != b);
        }

        public static bool4 NotEqual(half a, half4 b)
        {
            return new(a != b.x, a != b.y, a != b.z, a != b.w);
        }

        public static bool4 LessThan(half4 a, half4 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        }

        public static bool4 LessThan(half4 a, half b)
        {
            return new(a.x < b, a.y < b, a.z < b, a.w < b);
        }

        public static bool4 LessThan(half a, half4 b)
        {
            return new(a < b.x, a < b.y, a < b.z, a < b.w);
        }

        public static bool4 LessThanOrEqual(half4 a, half4 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        }

        public static bool4 LessThanOrEqual(half4 a, half b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        }

        public static bool4 LessThanOrEqual(half a, half4 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        }

        public static bool4 GreaterThan(half4 a, half4 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        }

        public static bool4 GreaterThan(half4 a, half b)
        {
            return new(a.x > b, a.y > b, a.z > b, a.w > b);
        }

        public static bool4 GreaterThan(half a, half4 b)
        {
            return new(a > b.x, a > b.y, a > b.z, a > b.w);
        }

        public static bool4 GreaterThanOrEqual(half4 a, half4 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        }

        public static bool4 GreaterThanOrEqual(half4 a, half b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        }

        public static bool4 GreaterThanOrEqual(half a, half4 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        }

        public static bool4 IsNaN(half4 value)
        {
            return new(DeltaMaths.IsNaN(value.x), DeltaMaths.IsNaN(value.y), DeltaMaths.IsNaN(value.z), DeltaMaths.IsNaN(value.w));
        }

        public static bool4 IsInfinity(half4 value)
        {
            return new(DeltaMaths.IsInfinity(value.x), DeltaMaths.IsInfinity(value.y), DeltaMaths.IsInfinity(value.z), DeltaMaths.IsInfinity(value.w));
        }

        public static bool4 IsFinite(half4 value)
        {
            return new(DeltaMaths.IsFinite(value.x), DeltaMaths.IsFinite(value.y), DeltaMaths.IsFinite(value.z), DeltaMaths.IsFinite(value.w));
        }
    }
}
