// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half3
    {

        public static bool operator ==(half3 left, half3 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z;
        }

        public static bool operator !=(half3 left, half3 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z;
        }

        public static half3 operator +(half3 value)
        {
            return new(+value.x, +value.y, +value.z);
        }

        public static half3 operator -(half3 value)
        {
            return new(-value.x, -value.y, -value.z);
        }

        public static half3 operator ++(half3 value)
        {
            return new(++value.x, ++value.y, ++value.z);
        }

        public static half3 operator --(half3 value)
        {
            return new(--value.x, --value.y, --value.z);
        }

        public static half3 operator +(half3 left, half3 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z);
        }

        public static half3 operator -(half3 left, half3 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z);
        }

        public static half3 operator *(half3 left, half3 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z);
        }

        public static half3 operator /(half3 left, half3 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z);
        }

        public static half3 operator +(half3 left, half right)
        {
            return new(left.x + right, left.y + right, left.z + right);
        }

        public static half3 operator +(half left, half3 right)
        {
            return new(left + right.x, left + right.y, left + right.z);
        }

        public static half3 operator -(half3 left, half right)
        {
            return new(left.x - right, left.y - right, left.z - right);
        }

        public static half3 operator -(half left, half3 right)
        {
            return new(left - right.x, left - right.y, left - right.z);
        }

        public static half3 operator *(half3 left, half right)
        {
            return new(left.x * right, left.y * right, left.z * right);
        }

        public static half3 operator *(half left, half3 right)
        {
            return new(left * right.x, left * right.y, left * right.z);
        }

        public static half3 operator /(half3 left, half right)
        {
            return new(left.x / right, left.y / right, left.z / right);
        }

        public static half3 operator /(half left, half3 right)
        {
            return new(left / right.x, left / right.y, left / right.z);
        }

        public static half3 operator %(half3 left, half3 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z);
        }

        public static half3 operator %(half3 left, half right)
        {
            return new(left.x % right, left.y % right, left.z % right);
        }

        public static half3 operator %(half left, half3 right)
        {
            return new(left % right.x, left % right.y, left % right.z);
        }

        public static bool3 operator <(half3 left, half3 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z);
        }

        public static bool3 operator <(half3 left, half right)
        {
            return new(left.x < right, left.y < right, left.z < right);
        }

        public static bool3 operator <(half left, half3 right)
        {
            return new(left < right.x, left < right.y, left < right.z);
        }

        public static bool3 operator <=(half3 left, half3 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z);
        }

        public static bool3 operator <=(half3 left, half right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right);
        }

        public static bool3 operator <=(half left, half3 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z);
        }

        public static bool3 operator >(half3 left, half3 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z);
        }

        public static bool3 operator >(half3 left, half right)
        {
            return new(left.x > right, left.y > right, left.z > right);
        }

        public static bool3 operator >(half left, half3 right)
        {
            return new(left > right.x, left > right.y, left > right.z);
        }

        public static bool3 operator >=(half3 left, half3 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z);
        }

        public static bool3 operator >=(half3 left, half right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right);
        }

        public static bool3 operator >=(half left, half3 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z);
        }

        public static explicit operator int3(half3 value)
        {
            return new int3((int)value.x, (int)value.y, (int)value.z);
        }
    }
}
