// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half2
    {

        public static half2 Exp(half2 value)
        {
            return new(DeltaMaths.Exp(value.x), DeltaMaths.Exp(value.y));
        }

        public static half2 Exp2(half2 value)
        {
            return new(DeltaMaths.Exp2(value.x), DeltaMaths.Exp2(value.y));
        }

        public static half2 Log(half2 value)
        {
            return new(DeltaMaths.Log(value.x), DeltaMaths.Log(value.y));
        }

        public static half2 Log2(half2 value)
        {
            return new(DeltaMaths.Log2(value.x), DeltaMaths.Log2(value.y));
        }

        public static half2 Log10(half2 value)
        {
            return new(DeltaMaths.Log10(value.x), DeltaMaths.Log10(value.y));
        }

        public static half2 Sqrt(half2 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y));
        }

        public static half2 InverseSqrt(half2 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y));
        }

        public static half2 Cbrt(half2 value)
        {
            return new(DeltaMaths.Cbrt(value.x), DeltaMaths.Cbrt(value.y));
        }

        public static half2 Pow(half2 a, half2 b)
        {
            return new(DeltaMaths.Pow(a.x, b.x), DeltaMaths.Pow(a.y, b.y));
        }

        public static half2 Pow(half2 a, half b)
        {
            return new(DeltaMaths.Pow(a.x, b), DeltaMaths.Pow(a.y, b));
        }

        public static half2 Pow(half a, half2 b)
        {
            return new(DeltaMaths.Pow(a, b.x), DeltaMaths.Pow(a, b.y));
        }
    }
}
