// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A vector of type half with 3 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct half3 : IEquatable<half3>, IComparable<half3>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public half x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public half y;

        [System.Runtime.Serialization.DataMember(Order = 2)]
        public half z;

        private half _padding;

        public static readonly half3 zero = new half3(half.Zero, half.Zero, half.Zero);

        public half3(half x, half y, half z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            _padding = half.Zero;
        }

        public half3(half value)
        {
            x = value;
            y = value;
            z = value;
            _padding = half.Zero;
        }

        public half3(half2 value)
        {
            x = value.x;
            y = value.y;
            z = half.Zero;
            _padding = half.Zero;
        }

        public half3(half3 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            _padding = half.Zero;
        }

        public half3(half4 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            _padding = half.Zero;
        }

        public half3(half x, half2 yz)
        {
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
            _padding = half.Zero;
        }

        public half3(half2 xy, half z)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
            _padding = half.Zero;
        }

        public half this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 3;

        public bool Equals(half3 other)
        {
            return x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z);
        }

        public override bool Equals(object? obj)
        {
            return obj is half3 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                hash = hash * 31 + z.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(half3 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            var zComparison = z.CompareTo(other.z);
            if (zComparison != 0) return zComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}, {z}");
        }

        public static half3 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 3)
                throw new FormatException("Expected 3 vector components.");
            return new(half.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[2].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static half3 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 3)
                throw new FormatException("Expected 3 vector components.");
            return new(half.Parse(values[0].Trim(), format), half.Parse(values[1].Trim(), format), half.Parse(values[2].Trim(), format));
        }
    }
}
