// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half4
    {

        public static bool operator ==(half4 left, half4 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z && left.w == right.w;
        }

        public static bool operator !=(half4 left, half4 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z || left.w != right.w;
        }

        public static half4 operator +(half4 value)
        {
            return new(+value.x, +value.y, +value.z, +value.w);
        }

        public static half4 operator -(half4 value)
        {
            return new(-value.x, -value.y, -value.z, -value.w);
        }

        public static half4 operator ++(half4 value)
        {
            return new(++value.x, ++value.y, ++value.z, ++value.w);
        }

        public static half4 operator --(half4 value)
        {
            return new(--value.x, --value.y, --value.z, --value.w);
        }

        public static half4 operator +(half4 left, half4 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z, left.w + right.w);
        }

        public static half4 operator -(half4 left, half4 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z, left.w - right.w);
        }

        public static half4 operator *(half4 left, half4 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z, left.w * right.w);
        }

        public static half4 operator /(half4 left, half4 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z, left.w / right.w);
        }

        public static half4 operator +(half4 left, half right)
        {
            return new(left.x + right, left.y + right, left.z + right, left.w + right);
        }

        public static half4 operator +(half left, half4 right)
        {
            return new(left + right.x, left + right.y, left + right.z, left + right.w);
        }

        public static half4 operator -(half4 left, half right)
        {
            return new(left.x - right, left.y - right, left.z - right, left.w - right);
        }

        public static half4 operator -(half left, half4 right)
        {
            return new(left - right.x, left - right.y, left - right.z, left - right.w);
        }

        public static half4 operator *(half4 left, half right)
        {
            return new(left.x * right, left.y * right, left.z * right, left.w * right);
        }

        public static half4 operator *(half left, half4 right)
        {
            return new(left * right.x, left * right.y, left * right.z, left * right.w);
        }

        public static half4 operator /(half4 left, half right)
        {
            return new(left.x / right, left.y / right, left.z / right, left.w / right);
        }

        public static half4 operator /(half left, half4 right)
        {
            return new(left / right.x, left / right.y, left / right.z, left / right.w);
        }

        public static half4 operator %(half4 left, half4 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z, left.w % right.w);
        }

        public static half4 operator %(half4 left, half right)
        {
            return new(left.x % right, left.y % right, left.z % right, left.w % right);
        }

        public static half4 operator %(half left, half4 right)
        {
            return new(left % right.x, left % right.y, left % right.z, left % right.w);
        }

        public static bool4 operator <(half4 left, half4 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z, left.w < right.w);
        }

        public static bool4 operator <(half4 left, half right)
        {
            return new(left.x < right, left.y < right, left.z < right, left.w < right);
        }

        public static bool4 operator <(half left, half4 right)
        {
            return new(left < right.x, left < right.y, left < right.z, left < right.w);
        }

        public static bool4 operator <=(half4 left, half4 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z, left.w <= right.w);
        }

        public static bool4 operator <=(half4 left, half right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right, left.w <= right);
        }

        public static bool4 operator <=(half left, half4 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z, left <= right.w);
        }

        public static bool4 operator >(half4 left, half4 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z, left.w > right.w);
        }

        public static bool4 operator >(half4 left, half right)
        {
            return new(left.x > right, left.y > right, left.z > right, left.w > right);
        }

        public static bool4 operator >(half left, half4 right)
        {
            return new(left > right.x, left > right.y, left > right.z, left > right.w);
        }

        public static bool4 operator >=(half4 left, half4 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z, left.w >= right.w);
        }

        public static bool4 operator >=(half4 left, half right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right, left.w >= right);
        }

        public static bool4 operator >=(half left, half4 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z, left >= right.w);
        }

        public static explicit operator int4(half4 value)
        {
            return new int4((int)value.x, (int)value.y, (int)value.z, (int)value.w);
        }
    }
}
