// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half3
    {

        public static half3 Sin(half3 value)
        {
            return new(DeltaMaths.Sin(value.x), DeltaMaths.Sin(value.y), DeltaMaths.Sin(value.z));
        }

        public static half3 Cos(half3 value)
        {
            return new(DeltaMaths.Cos(value.x), DeltaMaths.Cos(value.y), DeltaMaths.Cos(value.z));
        }

        public static half3 Tan(half3 value)
        {
            return new(DeltaMaths.Tan(value.x), DeltaMaths.Tan(value.y), DeltaMaths.Tan(value.z));
        }

        public static half3 Asin(half3 value)
        {
            return new(DeltaMaths.Asin(value.x), DeltaMaths.Asin(value.y), DeltaMaths.Asin(value.z));
        }

        public static half3 Acos(half3 value)
        {
            return new(DeltaMaths.Acos(value.x), DeltaMaths.Acos(value.y), DeltaMaths.Acos(value.z));
        }

        public static half3 Atan(half3 value)
        {
            return new(DeltaMaths.Atan(value.x), DeltaMaths.Atan(value.y), DeltaMaths.Atan(value.z));
        }

        public static half3 Atan2(half3 y, half3 x)
        {
            return new(DeltaMaths.Atan2(y.x, x.x), DeltaMaths.Atan2(y.y, x.y), DeltaMaths.Atan2(y.z, x.z));
        }

        public static half3 Atan2(half3 y, half x)
        {
            return new(DeltaMaths.Atan2(y.x, x), DeltaMaths.Atan2(y.y, x), DeltaMaths.Atan2(y.z, x));
        }

        public static half3 Atan2(half y, half3 x)
        {
            return new(DeltaMaths.Atan2(y, x.x), DeltaMaths.Atan2(y, x.y), DeltaMaths.Atan2(y, x.z));
        }

        public static half3 Sinh(half3 value)
        {
            return new(DeltaMaths.Sinh(value.x), DeltaMaths.Sinh(value.y), DeltaMaths.Sinh(value.z));
        }

        public static half3 Cosh(half3 value)
        {
            return new(DeltaMaths.Cosh(value.x), DeltaMaths.Cosh(value.y), DeltaMaths.Cosh(value.z));
        }

        public static half3 Tanh(half3 value)
        {
            return new(DeltaMaths.Tanh(value.x), DeltaMaths.Tanh(value.y), DeltaMaths.Tanh(value.z));
        }

        public static half3 Asinh(half3 value)
        {
            return new(DeltaMaths.Asinh(value.x), DeltaMaths.Asinh(value.y), DeltaMaths.Asinh(value.z));
        }

        public static half3 Acosh(half3 value)
        {
            return new(DeltaMaths.Acosh(value.x), DeltaMaths.Acosh(value.y), DeltaMaths.Acosh(value.z));
        }

        public static half3 Atanh(half3 value)
        {
            return new(DeltaMaths.Atanh(value.x), DeltaMaths.Atanh(value.y), DeltaMaths.Atanh(value.z));
        }
    }
}
