// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half3
    {

        public static half3 Select(half3 falseValue, half3 trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z);
        }

        public static half3 Select(half3 falseValue, half3 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z);
        }

        public static half3 Select(half falseValue, half trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue);
        }

        public static bool3 Equal(half3 a, half3 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z);
        }

        public static bool3 Equal(half3 a, half b)
        {
            return new(a.x == b, a.y == b, a.z == b);
        }

        public static bool3 Equal(half a, half3 b)
        {
            return new(a == b.x, a == b.y, a == b.z);
        }

        public static bool3 NotEqual(half3 a, half3 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z);
        }

        public static bool3 NotEqual(half3 a, half b)
        {
            return new(a.x != b, a.y != b, a.z != b);
        }

        public static bool3 NotEqual(half a, half3 b)
        {
            return new(a != b.x, a != b.y, a != b.z);
        }

        public static bool3 LessThan(half3 a, half3 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z);
        }

        public static bool3 LessThan(half3 a, half b)
        {
            return new(a.x < b, a.y < b, a.z < b);
        }

        public static bool3 LessThan(half a, half3 b)
        {
            return new(a < b.x, a < b.y, a < b.z);
        }

        public static bool3 LessThanOrEqual(half3 a, half3 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        }

        public static bool3 LessThanOrEqual(half3 a, half b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b);
        }

        public static bool3 LessThanOrEqual(half a, half3 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z);
        }

        public static bool3 GreaterThan(half3 a, half3 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z);
        }

        public static bool3 GreaterThan(half3 a, half b)
        {
            return new(a.x > b, a.y > b, a.z > b);
        }

        public static bool3 GreaterThan(half a, half3 b)
        {
            return new(a > b.x, a > b.y, a > b.z);
        }

        public static bool3 GreaterThanOrEqual(half3 a, half3 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        }

        public static bool3 GreaterThanOrEqual(half3 a, half b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b);
        }

        public static bool3 GreaterThanOrEqual(half a, half3 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z);
        }

        public static bool3 IsNaN(half3 value)
        {
            return new(DeltaMaths.IsNaN(value.x), DeltaMaths.IsNaN(value.y), DeltaMaths.IsNaN(value.z));
        }

        public static bool3 IsInfinity(half3 value)
        {
            return new(DeltaMaths.IsInfinity(value.x), DeltaMaths.IsInfinity(value.y), DeltaMaths.IsInfinity(value.z));
        }

        public static bool3 IsFinite(half3 value)
        {
            return new(DeltaMaths.IsFinite(value.x), DeltaMaths.IsFinite(value.y), DeltaMaths.IsFinite(value.z));
        }
    }
}
