// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half2
    {

        public static half2 Sin(half2 value)
        {
            return new(DeltaMaths.Sin(value.x), DeltaMaths.Sin(value.y));
        }

        public static half2 Cos(half2 value)
        {
            return new(DeltaMaths.Cos(value.x), DeltaMaths.Cos(value.y));
        }

        public static half2 Tan(half2 value)
        {
            return new(DeltaMaths.Tan(value.x), DeltaMaths.Tan(value.y));
        }

        public static half2 Asin(half2 value)
        {
            return new(DeltaMaths.Asin(value.x), DeltaMaths.Asin(value.y));
        }

        public static half2 Acos(half2 value)
        {
            return new(DeltaMaths.Acos(value.x), DeltaMaths.Acos(value.y));
        }

        public static half2 Atan(half2 value)
        {
            return new(DeltaMaths.Atan(value.x), DeltaMaths.Atan(value.y));
        }

        public static half2 Atan2(half2 y, half2 x)
        {
            return new(DeltaMaths.Atan2(y.x, x.x), DeltaMaths.Atan2(y.y, x.y));
        }

        public static half2 Atan2(half2 y, half x)
        {
            return new(DeltaMaths.Atan2(y.x, x), DeltaMaths.Atan2(y.y, x));
        }

        public static half2 Atan2(half y, half2 x)
        {
            return new(DeltaMaths.Atan2(y, x.x), DeltaMaths.Atan2(y, x.y));
        }

        public static half2 Sinh(half2 value)
        {
            return new(DeltaMaths.Sinh(value.x), DeltaMaths.Sinh(value.y));
        }

        public static half2 Cosh(half2 value)
        {
            return new(DeltaMaths.Cosh(value.x), DeltaMaths.Cosh(value.y));
        }

        public static half2 Tanh(half2 value)
        {
            return new(DeltaMaths.Tanh(value.x), DeltaMaths.Tanh(value.y));
        }

        public static half2 Asinh(half2 value)
        {
            return new(DeltaMaths.Asinh(value.x), DeltaMaths.Asinh(value.y));
        }

        public static half2 Acosh(half2 value)
        {
            return new(DeltaMaths.Acosh(value.x), DeltaMaths.Acosh(value.y));
        }

        public static half2 Atanh(half2 value)
        {
            return new(DeltaMaths.Atanh(value.x), DeltaMaths.Atanh(value.y));
        }
    }
}
