// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half2
    {

        public static half2 Select(half2 falseValue, half2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static half2 Select(half2 falseValue, half2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static half2 Select(half falseValue, half trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(half2 a, half2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(half2 a, half b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(half a, half2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(half2 a, half2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(half2 a, half b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(half a, half2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(half2 a, half2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(half2 a, half b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(half a, half2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(half2 a, half2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(half2 a, half b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(half a, half2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(half2 a, half2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(half2 a, half b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(half a, half2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(half2 a, half2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(half2 a, half b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(half a, half2 b)
        {
            return new(a >= b.x, a >= b.y);
        }

        public static bool2 IsNaN(half2 value)
        {
            return new(DeltaMaths.IsNaN(value.x), DeltaMaths.IsNaN(value.y));
        }

        public static bool2 IsInfinity(half2 value)
        {
            return new(DeltaMaths.IsInfinity(value.x), DeltaMaths.IsInfinity(value.y));
        }

        public static bool2 IsFinite(half2 value)
        {
            return new(DeltaMaths.IsFinite(value.x), DeltaMaths.IsFinite(value.y));
        }
    }
}
