// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    /// <summary>A vector of type half with 4 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct half4 : IEquatable<half4>, IComparable<half4>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public half x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public half y;

        [System.Runtime.Serialization.DataMember(Order = 2)]
        public half z;

        [System.Runtime.Serialization.DataMember(Order = 3)]
        public half w;

        public static readonly half4 zero = new half4(half.Zero, half.Zero, half.Zero, half.Zero);

        public half4(half x, half y, half z, half w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        public half4(half value)
        {
            x = value;
            y = value;
            z = value;
            w = value;
        }

        public half4(half2 value)
        {
            x = value.x;
            y = value.y;
            z = half.Zero;
            w = half.Zero;
        }

        public half4(half3 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            w = half.Zero;
        }

        public half4(half4 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            w = value.w;
        }

        public half4(half x, half y, half2 zw)
        {
            this.x = x;
            this.y = y;
            this.z = zw.x;
            this.w = zw.y;
        }

        public half4(half x, half2 yz, half w)
        {
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
            this.w = w;
        }

        public half4(half x, half3 yzw)
        {
            this.x = x;
            this.y = yzw.x;
            this.z = yzw.y;
            this.w = yzw.z;
        }

        public half4(half2 xy, half z, half w)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
            this.w = w;
        }

        public half4(half2 xy, half2 zw)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = zw.x;
            this.w = zw.y;
        }

        public half4(half3 xyz, half w)
        {
            this.x = xyz.x;
            this.y = xyz.y;
            this.z = xyz.z;
            this.w = w;
        }

        public half this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 4;

        public bool Equals(half4 other)
        {
            return x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z) && w.Equals(other.w);
        }

        public override bool Equals(object? obj)
        {
            return obj is half4 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                hash = hash * 31 + z.GetHashCode();
                hash = hash * 31 + w.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(half4 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            var zComparison = z.CompareTo(other.z);
            if (zComparison != 0) return zComparison;
            var wComparison = w.CompareTo(other.w);
            if (wComparison != 0) return wComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}, {z}, {w}");
        }

        public static half4 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 4)
                throw new FormatException("Expected 4 vector components.");
            return new(half.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[2].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[3].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static half4 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 4)
                throw new FormatException("Expected 4 vector components.");
            return new(half.Parse(values[0].Trim(), format), half.Parse(values[1].Trim(), format), half.Parse(values[2].Trim(), format), half.Parse(values[3].Trim(), format));
        }
    }
}
