// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half2
    {

        public static half Dot(half2 a, half2 b)
        {
            return a.x * b.x + a.y * b.y;
        }

        public static half SqrLength(half2 value)
        {
            return value.x * value.x + value.y * value.y;
        }

        public static half Length(half2 value)
        {
            return DeltaMaths.Sqrt(SqrLength(value));
        }

        public static half Distance(half2 a, half2 b)
        {
            return Length(a - b);
        }

        public static half SqrDistance(half2 a, half2 b)
        {
            return SqrLength(a - b);
        }

        public static half2 Normalize(half2 value)
        {
            return value / Length(value);
        }

        public static half2 NormalizeSafe(half2 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? zero : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half2 NormalizeSafe(half2 value, half2 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? fallback : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half2 FaceForward(half2 N, half2 I, half2 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static half2 Reflect(half2 I, half2 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static half2 Refract(half2 I, half2 N, half eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + DeltaMaths.Sqrt(k)) * N;
        }

        public static half2 Project(half2 value, half2 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static half2 ProjectSafe(half2 value, half2 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static half2 ClampLength(half2 value, half maxLength)
        {
            maxLength = DeltaMaths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * DeltaMaths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static half2 MoveTowards(half2 current, half2 target, half maxDelta)
        {
            maxDelta = DeltaMaths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * DeltaMaths.InverseSqrt(sqrDistance);
        }

        public static half2 SmoothDamp(half2 source, half2 target, ref half2 velocity, half smoothTime, half deltaTime)
        {
            return new(DeltaMaths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime));
        }
    }
}
