// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half2
    {

        public static bool operator ==(half2 left, half2 right)
        {
            return left.x == right.x && left.y == right.y;
        }

        public static bool operator !=(half2 left, half2 right)
        {
            return left.x != right.x || left.y != right.y;
        }

        public static half2 operator +(half2 value)
        {
            return new(+value.x, +value.y);
        }

        public static half2 operator -(half2 value)
        {
            return new(-value.x, -value.y);
        }

        public static half2 operator ++(half2 value)
        {
            return new(++value.x, ++value.y);
        }

        public static half2 operator --(half2 value)
        {
            return new(--value.x, --value.y);
        }

        public static half2 operator +(half2 left, half2 right)
        {
            return new(left.x + right.x, left.y + right.y);
        }

        public static half2 operator -(half2 left, half2 right)
        {
            return new(left.x - right.x, left.y - right.y);
        }

        public static half2 operator *(half2 left, half2 right)
        {
            return new(left.x * right.x, left.y * right.y);
        }

        public static half2 operator /(half2 left, half2 right)
        {
            return new(left.x / right.x, left.y / right.y);
        }

        public static half2 operator +(half2 left, half right)
        {
            return new(left.x + right, left.y + right);
        }

        public static half2 operator +(half left, half2 right)
        {
            return new(left + right.x, left + right.y);
        }

        public static half2 operator -(half2 left, half right)
        {
            return new(left.x - right, left.y - right);
        }

        public static half2 operator -(half left, half2 right)
        {
            return new(left - right.x, left - right.y);
        }

        public static half2 operator *(half2 left, half right)
        {
            return new(left.x * right, left.y * right);
        }

        public static half2 operator *(half left, half2 right)
        {
            return new(left * right.x, left * right.y);
        }

        public static half2 operator /(half2 left, half right)
        {
            return new(left.x / right, left.y / right);
        }

        public static half2 operator /(half left, half2 right)
        {
            return new(left / right.x, left / right.y);
        }

        public static half2 operator %(half2 left, half2 right)
        {
            return new(left.x % right.x, left.y % right.y);
        }

        public static half2 operator %(half2 left, half right)
        {
            return new(left.x % right, left.y % right);
        }

        public static half2 operator %(half left, half2 right)
        {
            return new(left % right.x, left % right.y);
        }

        public static bool2 operator <(half2 left, half2 right)
        {
            return new(left.x < right.x, left.y < right.y);
        }

        public static bool2 operator <(half2 left, half right)
        {
            return new(left.x < right, left.y < right);
        }

        public static bool2 operator <(half left, half2 right)
        {
            return new(left < right.x, left < right.y);
        }

        public static bool2 operator <=(half2 left, half2 right)
        {
            return new(left.x <= right.x, left.y <= right.y);
        }

        public static bool2 operator <=(half2 left, half right)
        {
            return new(left.x <= right, left.y <= right);
        }

        public static bool2 operator <=(half left, half2 right)
        {
            return new(left <= right.x, left <= right.y);
        }

        public static bool2 operator >(half2 left, half2 right)
        {
            return new(left.x > right.x, left.y > right.y);
        }

        public static bool2 operator >(half2 left, half right)
        {
            return new(left.x > right, left.y > right);
        }

        public static bool2 operator >(half left, half2 right)
        {
            return new(left > right.x, left > right.y);
        }

        public static bool2 operator >=(half2 left, half2 right)
        {
            return new(left.x >= right.x, left.y >= right.y);
        }

        public static bool2 operator >=(half2 left, half right)
        {
            return new(left.x >= right, left.y >= right);
        }

        public static bool2 operator >=(half left, half2 right)
        {
            return new(left >= right.x, left >= right.y);
        }

        public static explicit operator int2(half2 value)
        {
            return new int2((int)value.x, (int)value.y);
        }
    }
}
