// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half4
    {

        public static half Dot(half4 a, half4 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
        }

        public static half SqrLength(half4 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z + value.w * value.w;
        }

        public static half Length(half4 value)
        {
            return DeltaMaths.Sqrt(SqrLength(value));
        }

        public static half Distance(half4 a, half4 b)
        {
            return Length(a - b);
        }

        public static half SqrDistance(half4 a, half4 b)
        {
            return SqrLength(a - b);
        }

        public static half4 Normalize(half4 value)
        {
            return value / Length(value);
        }

        public static half4 NormalizeSafe(half4 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? zero : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half4 NormalizeSafe(half4 value, half4 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? fallback : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half4 FaceForward(half4 N, half4 I, half4 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static half4 Reflect(half4 I, half4 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static half4 Refract(half4 I, half4 N, half eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + DeltaMaths.Sqrt(k)) * N;
        }

        public static half4 Project(half4 value, half4 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static half4 ProjectSafe(half4 value, half4 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static half4 ClampLength(half4 value, half maxLength)
        {
            maxLength = DeltaMaths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * DeltaMaths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static half4 MoveTowards(half4 current, half4 target, half maxDelta)
        {
            maxDelta = DeltaMaths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * DeltaMaths.InverseSqrt(sqrDistance);
        }

        public static half4 SmoothDamp(half4 source, half4 target, ref half4 velocity, half smoothTime, half deltaTime)
        {
            return new(DeltaMaths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.w, target.w, ref velocity.w, smoothTime, deltaTime));
        }
    }
}
