// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half4
    {

        public static half4 Min(half4 a, half4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static half4 Min(half4 a, half b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static half4 Min(half a, half4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static half4 Max(half4 a, half4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static half4 Max(half4 a, half b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static half4 Max(half a, half4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static half4 Clamp(half4 value, half min, half max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static half4 Clamp(half4 value, half4 min, half4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static half4 Abs(half4 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z), DeltaMaths.Abs(value.w));
        }

        public static half4 Sign(half4 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z), DeltaMaths.Sign(value.w));
        }

        public static half Sum(half4 value)
        {
            return value.x + value.y + value.z + value.w;
        }

        public static half4 Lerp(half4 a, half4 b, half t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t), DeltaMaths.Lerp(a.z, b.z, t), DeltaMaths.Lerp(a.w, b.w, t));
        }

        public static half4 Lerp(half4 a, half4 b, half4 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y), DeltaMaths.Lerp(a.z, b.z, t.z), DeltaMaths.Lerp(a.w, b.w, t.w));
        }

        public static half4 InvLerp(half4 edge0, half4 edge1, half4 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y), DeltaMaths.InvLerp(edge0.z, edge1.z, value.z), DeltaMaths.InvLerp(edge0.w, edge1.w, value.w));
        }

        public static half4 InvLerp(half4 edge0, half4 edge1, half value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value), DeltaMaths.InvLerp(edge0.z, edge1.z, value), DeltaMaths.InvLerp(edge0.w, edge1.w, value));
        }

        public static half4 Smoothstep(half4 edge0, half4 edge1, half4 value)
        {
            return new(DeltaMaths.Smoothstep(edge0.x, edge1.x, value.x), DeltaMaths.Smoothstep(edge0.y, edge1.y, value.y), DeltaMaths.Smoothstep(edge0.z, edge1.z, value.z), DeltaMaths.Smoothstep(edge0.w, edge1.w, value.w));
        }

        public static half4 Smoothstep(half edge0, half edge1, half4 value)
        {
            return new(DeltaMaths.Smoothstep(edge0, edge1, value.x), DeltaMaths.Smoothstep(edge0, edge1, value.y), DeltaMaths.Smoothstep(edge0, edge1, value.z), DeltaMaths.Smoothstep(edge0, edge1, value.w));
        }

        public static half4 Step(half4 edge, half4 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y), DeltaMaths.Step(edge.z, value.z), DeltaMaths.Step(edge.w, value.w));
        }

        public static half4 Step(half edge, half4 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y), DeltaMaths.Step(edge, value.z), DeltaMaths.Step(edge, value.w));
        }

        public static half4 Saturate(half4 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y), DeltaMaths.Saturate(value.z), DeltaMaths.Saturate(value.w));
        }

        public static half4 Fma(half4 a, half4 b, half4 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y), DeltaMaths.Fma(a.z, b.z, c.z), DeltaMaths.Fma(a.w, b.w, c.w));
        }

        public static half4 Remap(half4 value, half4 sourceFrom, half4 sourceTo, half4 targetFrom, half4 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), DeltaMaths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z), DeltaMaths.Remap(value.w, sourceFrom.w, sourceTo.w, targetFrom.w, targetTo.w));
        }

        public static half4 Mod(half4 x, half4 y)
        {
            return new(DeltaMaths.Mod(x.x, y.x), DeltaMaths.Mod(x.y, y.y), DeltaMaths.Mod(x.z, y.z), DeltaMaths.Mod(x.w, y.w));
        }

        public static half4 Mod(half4 x, half y)
        {
            return new(DeltaMaths.Mod(x.x, y), DeltaMaths.Mod(x.y, y), DeltaMaths.Mod(x.z, y), DeltaMaths.Mod(x.w, y));
        }

        public static half4 Modf(half4 value, out half4 integerPart)
        {
            var fractionalx = DeltaMaths.Modf(value.x, out var integerx);
            var fractionaly = DeltaMaths.Modf(value.y, out var integery);
            var fractionalz = DeltaMaths.Modf(value.z, out var integerz);
            var fractionalw = DeltaMaths.Modf(value.w, out var integerw);
            integerPart = new(integerx, integery, integerz, integerw);
            return new(fractionalx, fractionaly, fractionalz, fractionalw);
        }

        public static half4 Frexp(half4 value, out int4 exponent)
        {
            var mantissax = DeltaMaths.Frexp(value.x, out var exponentx);
            var mantissay = DeltaMaths.Frexp(value.y, out var exponenty);
            var mantissaz = DeltaMaths.Frexp(value.z, out var exponentz);
            var mantissaw = DeltaMaths.Frexp(value.w, out var exponentw);
            exponent = new(exponentx, exponenty, exponentz, exponentw);
            return new(mantissax, mantissay, mantissaz, mantissaw);
        }

        public static half4 Ldexp(half4 value, int4 exponent)
        {
            return new(DeltaMaths.Ldexp(value.x, exponent.x), DeltaMaths.Ldexp(value.y, exponent.y), DeltaMaths.Ldexp(value.z, exponent.z), DeltaMaths.Ldexp(value.w, exponent.w));
        }

        public static half4 Floor(half4 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y), DeltaMaths.Floor(value.z), DeltaMaths.Floor(value.w));
        }

        public static half4 Ceil(half4 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y), DeltaMaths.Ceil(value.z), DeltaMaths.Ceil(value.w));
        }

        public static half4 Round(half4 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y), DeltaMaths.Round(value.z), DeltaMaths.Round(value.w));
        }

        public static half4 RoundEven(half4 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y), DeltaMaths.RoundEven(value.z), DeltaMaths.RoundEven(value.w));
        }

        public static half4 Truncate(half4 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y), DeltaMaths.Truncate(value.z), DeltaMaths.Truncate(value.w));
        }

        public static half4 Fract(half4 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y), DeltaMaths.Fract(value.z), DeltaMaths.Fract(value.w));
        }

        public static half4 Radians(half4 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y), DeltaMaths.Radians(value.z), DeltaMaths.Radians(value.w));
        }

        public static half4 Degrees(half4 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y), DeltaMaths.Degrees(value.z), DeltaMaths.Degrees(value.w));
        }
    }
}
