// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half3
    {

        public static half Dot(half3 a, half3 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z;
        }

        public static half SqrLength(half3 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z;
        }

        public static half Length(half3 value)
        {
            return DeltaMaths.Sqrt(SqrLength(value));
        }

        public static half Distance(half3 a, half3 b)
        {
            return Length(a - b);
        }

        public static half SqrDistance(half3 a, half3 b)
        {
            return SqrLength(a - b);
        }

        public static half3 Normalize(half3 value)
        {
            return value / Length(value);
        }

        public static half3 NormalizeSafe(half3 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? zero : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half3 NormalizeSafe(half3 value, half3 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= half.Epsilon ? fallback : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static half3 FaceForward(half3 N, half3 I, half3 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static half3 Reflect(half3 I, half3 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static half3 Refract(half3 I, half3 N, half eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + DeltaMaths.Sqrt(k)) * N;
        }

        public static half3 Project(half3 value, half3 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static half3 ProjectSafe(half3 value, half3 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static half3 ClampLength(half3 value, half maxLength)
        {
            maxLength = DeltaMaths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * DeltaMaths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static half3 MoveTowards(half3 current, half3 target, half maxDelta)
        {
            maxDelta = DeltaMaths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * DeltaMaths.InverseSqrt(sqrDistance);
        }

        public static half3 SmoothDamp(half3 source, half3 target, ref half3 velocity, half smoothTime, half deltaTime)
        {
            return new(DeltaMaths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime));
        }

        public static half3 Cross(half3 a, half3 b)
        {
            return new(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
        }
    }
}
