// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half4
    {

        public static half4 Sin(half4 value)
        {
            return new(DeltaMaths.Sin(value.x), DeltaMaths.Sin(value.y), DeltaMaths.Sin(value.z), DeltaMaths.Sin(value.w));
        }

        public static half4 Cos(half4 value)
        {
            return new(DeltaMaths.Cos(value.x), DeltaMaths.Cos(value.y), DeltaMaths.Cos(value.z), DeltaMaths.Cos(value.w));
        }

        public static half4 Tan(half4 value)
        {
            return new(DeltaMaths.Tan(value.x), DeltaMaths.Tan(value.y), DeltaMaths.Tan(value.z), DeltaMaths.Tan(value.w));
        }

        public static half4 Asin(half4 value)
        {
            return new(DeltaMaths.Asin(value.x), DeltaMaths.Asin(value.y), DeltaMaths.Asin(value.z), DeltaMaths.Asin(value.w));
        }

        public static half4 Acos(half4 value)
        {
            return new(DeltaMaths.Acos(value.x), DeltaMaths.Acos(value.y), DeltaMaths.Acos(value.z), DeltaMaths.Acos(value.w));
        }

        public static half4 Atan(half4 value)
        {
            return new(DeltaMaths.Atan(value.x), DeltaMaths.Atan(value.y), DeltaMaths.Atan(value.z), DeltaMaths.Atan(value.w));
        }

        public static half4 Atan2(half4 y, half4 x)
        {
            return new(DeltaMaths.Atan2(y.x, x.x), DeltaMaths.Atan2(y.y, x.y), DeltaMaths.Atan2(y.z, x.z), DeltaMaths.Atan2(y.w, x.w));
        }

        public static half4 Atan2(half4 y, half x)
        {
            return new(DeltaMaths.Atan2(y.x, x), DeltaMaths.Atan2(y.y, x), DeltaMaths.Atan2(y.z, x), DeltaMaths.Atan2(y.w, x));
        }

        public static half4 Atan2(half y, half4 x)
        {
            return new(DeltaMaths.Atan2(y, x.x), DeltaMaths.Atan2(y, x.y), DeltaMaths.Atan2(y, x.z), DeltaMaths.Atan2(y, x.w));
        }

        public static half4 Sinh(half4 value)
        {
            return new(DeltaMaths.Sinh(value.x), DeltaMaths.Sinh(value.y), DeltaMaths.Sinh(value.z), DeltaMaths.Sinh(value.w));
        }

        public static half4 Cosh(half4 value)
        {
            return new(DeltaMaths.Cosh(value.x), DeltaMaths.Cosh(value.y), DeltaMaths.Cosh(value.z), DeltaMaths.Cosh(value.w));
        }

        public static half4 Tanh(half4 value)
        {
            return new(DeltaMaths.Tanh(value.x), DeltaMaths.Tanh(value.y), DeltaMaths.Tanh(value.z), DeltaMaths.Tanh(value.w));
        }

        public static half4 Asinh(half4 value)
        {
            return new(DeltaMaths.Asinh(value.x), DeltaMaths.Asinh(value.y), DeltaMaths.Asinh(value.z), DeltaMaths.Asinh(value.w));
        }

        public static half4 Acosh(half4 value)
        {
            return new(DeltaMaths.Acosh(value.x), DeltaMaths.Acosh(value.y), DeltaMaths.Acosh(value.z), DeltaMaths.Acosh(value.w));
        }

        public static half4 Atanh(half4 value)
        {
            return new(DeltaMaths.Atanh(value.x), DeltaMaths.Atanh(value.y), DeltaMaths.Atanh(value.z), DeltaMaths.Atanh(value.w));
        }
    }
}
