// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    /// <summary>A vector of type half with 2 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct half2 : IEquatable<half2>, IComparable<half2>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public half x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public half y;

        public static readonly half2 zero = new half2(half.Zero, half.Zero);

        public half2(half x, half y)
        {
            this.x = x;
            this.y = y;
        }

        public half2(half value)
        {
            x = value;
            y = value;
        }

        public half2(half2 value)
        {
            x = value.x;
            y = value.y;
        }

        public half2(half3 value)
        {
            x = value.x;
            y = value.y;
        }

        public half2(half4 value)
        {
            x = value.x;
            y = value.y;
        }

        public half this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 2;

        public bool Equals(half2 other)
        {
            return x.Equals(other.x) && y.Equals(other.y);
        }

        public override bool Equals(object? obj)
        {
            return obj is half2 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(half2 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}");
        }

        public static half2 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 2)
                throw new FormatException("Expected 2 vector components.");
            return new(half.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), half.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static half2 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 2)
                throw new FormatException("Expected 2 vector components.");
            return new(half.Parse(values[0].Trim(), format), half.Parse(values[1].Trim(), format));
        }
    }
}
