// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct half2
    {

        public static half2 Min(half2 a, half2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static half2 Min(half2 a, half b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static half2 Min(half a, half2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static half2 Max(half2 a, half2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static half2 Max(half2 a, half b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static half2 Max(half a, half2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static half2 Clamp(half2 value, half min, half max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static half2 Clamp(half2 value, half2 min, half2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static half2 Abs(half2 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y));
        }

        public static half2 Sign(half2 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y));
        }

        public static half Sum(half2 value)
        {
            return value.x + value.y;
        }

        public static half2 Lerp(half2 a, half2 b, half t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t));
        }

        public static half2 Lerp(half2 a, half2 b, half2 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y));
        }

        public static half2 InvLerp(half2 edge0, half2 edge1, half2 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static half2 InvLerp(half2 edge0, half2 edge1, half value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value));
        }

        public static half2 Smoothstep(half2 edge0, half2 edge1, half2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0.x, edge1.x, value.x), DeltaMaths.Smoothstep(edge0.y, edge1.y, value.y));
        }

        public static half2 Smoothstep(half edge0, half edge1, half2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0, edge1, value.x), DeltaMaths.Smoothstep(edge0, edge1, value.y));
        }

        public static half2 Step(half2 edge, half2 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y));
        }

        public static half2 Step(half edge, half2 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y));
        }

        public static half2 Saturate(half2 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y));
        }

        public static half2 Fma(half2 a, half2 b, half2 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y));
        }

        public static half2 Remap(half2 value, half2 sourceFrom, half2 sourceTo, half2 targetFrom, half2 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static half2 Mod(half2 x, half2 y)
        {
            return new(DeltaMaths.Mod(x.x, y.x), DeltaMaths.Mod(x.y, y.y));
        }

        public static half2 Mod(half2 x, half y)
        {
            return new(DeltaMaths.Mod(x.x, y), DeltaMaths.Mod(x.y, y));
        }

        public static half2 Modf(half2 value, out half2 integerPart)
        {
            var fractionalx = DeltaMaths.Modf(value.x, out var integerx);
            var fractionaly = DeltaMaths.Modf(value.y, out var integery);
            integerPart = new(integerx, integery);
            return new(fractionalx, fractionaly);
        }

        public static half2 Frexp(half2 value, out int2 exponent)
        {
            var mantissax = DeltaMaths.Frexp(value.x, out var exponentx);
            var mantissay = DeltaMaths.Frexp(value.y, out var exponenty);
            exponent = new(exponentx, exponenty);
            return new(mantissax, mantissay);
        }

        public static half2 Ldexp(half2 value, int2 exponent)
        {
            return new(DeltaMaths.Ldexp(value.x, exponent.x), DeltaMaths.Ldexp(value.y, exponent.y));
        }

        public static half2 Floor(half2 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y));
        }

        public static half2 Ceil(half2 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y));
        }

        public static half2 Round(half2 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y));
        }

        public static half2 RoundEven(half2 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y));
        }

        public static half2 Truncate(half2 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y));
        }

        public static half2 Fract(half2 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y));
        }

        public static half2 Radians(half2 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y));
        }

        public static half2 Degrees(half2 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y));
        }
    }
}
