// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct half4
    {

        public static half4 Exp(half4 value)
        {
            return new(DeltaMaths.Exp(value.x), DeltaMaths.Exp(value.y), DeltaMaths.Exp(value.z), DeltaMaths.Exp(value.w));
        }

        public static half4 Exp2(half4 value)
        {
            return new(DeltaMaths.Exp2(value.x), DeltaMaths.Exp2(value.y), DeltaMaths.Exp2(value.z), DeltaMaths.Exp2(value.w));
        }

        public static half4 Log(half4 value)
        {
            return new(DeltaMaths.Log(value.x), DeltaMaths.Log(value.y), DeltaMaths.Log(value.z), DeltaMaths.Log(value.w));
        }

        public static half4 Log2(half4 value)
        {
            return new(DeltaMaths.Log2(value.x), DeltaMaths.Log2(value.y), DeltaMaths.Log2(value.z), DeltaMaths.Log2(value.w));
        }

        public static half4 Log10(half4 value)
        {
            return new(DeltaMaths.Log10(value.x), DeltaMaths.Log10(value.y), DeltaMaths.Log10(value.z), DeltaMaths.Log10(value.w));
        }

        public static half4 Sqrt(half4 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y), DeltaMaths.Sqrt(value.z), DeltaMaths.Sqrt(value.w));
        }

        public static half4 InverseSqrt(half4 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y), DeltaMaths.InverseSqrt(value.z), DeltaMaths.InverseSqrt(value.w));
        }

        public static half4 Cbrt(half4 value)
        {
            return new(DeltaMaths.Cbrt(value.x), DeltaMaths.Cbrt(value.y), DeltaMaths.Cbrt(value.z), DeltaMaths.Cbrt(value.w));
        }

        public static half4 Pow(half4 a, half4 b)
        {
            return new(DeltaMaths.Pow(a.x, b.x), DeltaMaths.Pow(a.y, b.y), DeltaMaths.Pow(a.z, b.z), DeltaMaths.Pow(a.w, b.w));
        }

        public static half4 Pow(half4 a, half b)
        {
            return new(DeltaMaths.Pow(a.x, b), DeltaMaths.Pow(a.y, b), DeltaMaths.Pow(a.z, b), DeltaMaths.Pow(a.w, b));
        }

        public static half4 Pow(half a, half4 b)
        {
            return new(DeltaMaths.Pow(a, b.x), DeltaMaths.Pow(a, b.y), DeltaMaths.Pow(a, b.z), DeltaMaths.Pow(a, b.w));
        }
    }
}
