// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct int2
    {

        public static int2 Min(int2 a, int2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static int2 Min(int2 a, int b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static int2 Min(int a, int2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static int2 Max(int2 a, int2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static int2 Max(int2 a, int b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static int2 Max(int a, int2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static int2 Clamp(int2 value, int min, int max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static int2 Clamp(int2 value, int2 min, int2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static int2 Abs(int2 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y));
        }

        public static int2 Sign(int2 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y));
        }

        public static int Sum(int2 value)
        {
            return value.x + value.y;
        }

        public static int2 BitCount(int2 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y));
        }

        public static int2 FindLSB(int2 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y));
        }

        public static int2 FindMSB(int2 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y));
        }

        public static int2 BitfieldReverse(int2 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y));
        }

        public static int2 BitfieldExtract(int2 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits));
        }

        public static int2 BitfieldInsert(int2 baseValue, int2 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits));
        }

        public static void ImulExtended(int2 a, int2 b, out int2 msb, out int2 lsb)
        {
            DeltaMaths.ImulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.ImulExtended(a.y, b.y, out var msby, out var lsby);
            msb = new(msbx, msby);
            lsb = new(lsbx, lsby);
        }
    }
}
