// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct int3
    {

        public static int3 Min(int3 a, int3 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z));
        }

        public static int3 Min(int3 a, int b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b));
        }

        public static int3 Min(int a, int3 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z));
        }

        public static int3 Max(int3 a, int3 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z));
        }

        public static int3 Max(int3 a, int b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b));
        }

        public static int3 Max(int a, int3 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z));
        }

        public static int3 Clamp(int3 value, int min, int max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max));
        }

        public static int3 Clamp(int3 value, int3 min, int3 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z));
        }

        public static int3 Abs(int3 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z));
        }

        public static int3 Sign(int3 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z));
        }

        public static int Sum(int3 value)
        {
            return value.x + value.y + value.z;
        }

        public static int3 BitCount(int3 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y), DeltaMaths.BitCount(value.z));
        }

        public static int3 FindLSB(int3 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y), DeltaMaths.FindLSB(value.z));
        }

        public static int3 FindMSB(int3 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y), DeltaMaths.FindMSB(value.z));
        }

        public static int3 BitfieldReverse(int3 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y), DeltaMaths.BitfieldReverse(value.z));
        }

        public static int3 BitfieldExtract(int3 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits), DeltaMaths.BitfieldExtract(value.z, offset, bits));
        }

        public static int3 BitfieldInsert(int3 baseValue, int3 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits), DeltaMaths.BitfieldInsert(baseValue.z, insert.z, offset, bits));
        }

        public static void ImulExtended(int3 a, int3 b, out int3 msb, out int3 lsb)
        {
            DeltaMaths.ImulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.ImulExtended(a.y, b.y, out var msby, out var lsby);
            DeltaMaths.ImulExtended(a.z, b.z, out var msbz, out var lsbz);
            msb = new(msbx, msby, msbz);
            lsb = new(lsbx, lsby, lsbz);
        }
    }
}
