// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct int4
    {

        public static int4 Min(int4 a, int4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static int4 Min(int4 a, int b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static int4 Min(int a, int4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static int4 Max(int4 a, int4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static int4 Max(int4 a, int b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static int4 Max(int a, int4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static int4 Clamp(int4 value, int min, int max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static int4 Clamp(int4 value, int4 min, int4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static int4 Abs(int4 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z), DeltaMaths.Abs(value.w));
        }

        public static int4 Sign(int4 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z), DeltaMaths.Sign(value.w));
        }

        public static int Sum(int4 value)
        {
            return value.x + value.y + value.z + value.w;
        }

        public static int4 BitCount(int4 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y), DeltaMaths.BitCount(value.z), DeltaMaths.BitCount(value.w));
        }

        public static int4 FindLSB(int4 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y), DeltaMaths.FindLSB(value.z), DeltaMaths.FindLSB(value.w));
        }

        public static int4 FindMSB(int4 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y), DeltaMaths.FindMSB(value.z), DeltaMaths.FindMSB(value.w));
        }

        public static int4 BitfieldReverse(int4 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y), DeltaMaths.BitfieldReverse(value.z), DeltaMaths.BitfieldReverse(value.w));
        }

        public static int4 BitfieldExtract(int4 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits), DeltaMaths.BitfieldExtract(value.z, offset, bits), DeltaMaths.BitfieldExtract(value.w, offset, bits));
        }

        public static int4 BitfieldInsert(int4 baseValue, int4 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits), DeltaMaths.BitfieldInsert(baseValue.z, insert.z, offset, bits), DeltaMaths.BitfieldInsert(baseValue.w, insert.w, offset, bits));
        }

        public static void ImulExtended(int4 a, int4 b, out int4 msb, out int4 lsb)
        {
            DeltaMaths.ImulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.ImulExtended(a.y, b.y, out var msby, out var lsby);
            DeltaMaths.ImulExtended(a.z, b.z, out var msbz, out var lsbz);
            DeltaMaths.ImulExtended(a.w, b.w, out var msbw, out var lsbw);
            msb = new(msbx, msby, msbz, msbw);
            lsb = new(lsbx, lsby, lsbz, lsbw);
        }
    }
}
