// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta
{
    public partial struct uint2
    {

        public static uint2 Min(uint2 a, uint2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static uint2 Min(uint2 a, uint b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static uint2 Min(uint a, uint2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static uint2 Max(uint2 a, uint2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static uint2 Max(uint2 a, uint b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static uint2 Max(uint a, uint2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static uint2 Clamp(uint2 value, uint min, uint max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static uint2 Clamp(uint2 value, uint2 min, uint2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static uint Sum(uint2 value)
        {
            return value.x + value.y;
        }

        public static int2 BitCount(uint2 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y));
        }

        public static int2 FindLSB(uint2 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y));
        }

        public static int2 FindMSB(uint2 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y));
        }

        public static uint2 BitfieldReverse(uint2 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y));
        }

        public static uint2 BitfieldExtract(uint2 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits));
        }

        public static uint2 BitfieldInsert(uint2 baseValue, uint2 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits));
        }

        public static uint2 UaddCarry(uint2 a, uint2 b, out uint2 carry)
        {
            var resultx = DeltaMaths.UaddCarry(a.x, b.x, out var carryx);
            var resulty = DeltaMaths.UaddCarry(a.y, b.y, out var carryy);
            carry = new(carryx, carryy);
            return new(resultx, resulty);
        }

        public static uint2 UsubBorrow(uint2 a, uint2 b, out uint2 borrow)
        {
            var resultx = DeltaMaths.UsubBorrow(a.x, b.x, out var borrowx);
            var resulty = DeltaMaths.UsubBorrow(a.y, b.y, out var borrowy);
            borrow = new(borrowx, borrowy);
            return new(resultx, resulty);
        }

        public static void UmulExtended(uint2 a, uint2 b, out uint2 msb, out uint2 lsb)
        {
            DeltaMaths.UmulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.UmulExtended(a.y, b.y, out var msby, out var lsby);
            msb = new(msbx, msby);
            lsb = new(lsbx, lsby);
        }
    }
}
