// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct uint3
    {

        public static uint3 Min(uint3 a, uint3 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z));
        }

        public static uint3 Min(uint3 a, uint b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b));
        }

        public static uint3 Min(uint a, uint3 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z));
        }

        public static uint3 Max(uint3 a, uint3 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z));
        }

        public static uint3 Max(uint3 a, uint b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b));
        }

        public static uint3 Max(uint a, uint3 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z));
        }

        public static uint3 Clamp(uint3 value, uint min, uint max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max));
        }

        public static uint3 Clamp(uint3 value, uint3 min, uint3 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z));
        }

        public static uint Sum(uint3 value)
        {
            return value.x + value.y + value.z;
        }

        public static int3 BitCount(uint3 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y), DeltaMaths.BitCount(value.z));
        }

        public static int3 FindLSB(uint3 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y), DeltaMaths.FindLSB(value.z));
        }

        public static int3 FindMSB(uint3 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y), DeltaMaths.FindMSB(value.z));
        }

        public static uint3 BitfieldReverse(uint3 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y), DeltaMaths.BitfieldReverse(value.z));
        }

        public static uint3 BitfieldExtract(uint3 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits), DeltaMaths.BitfieldExtract(value.z, offset, bits));
        }

        public static uint3 BitfieldInsert(uint3 baseValue, uint3 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits), DeltaMaths.BitfieldInsert(baseValue.z, insert.z, offset, bits));
        }

        public static uint3 UaddCarry(uint3 a, uint3 b, out uint3 carry)
        {
            var resultx = DeltaMaths.UaddCarry(a.x, b.x, out var carryx);
            var resulty = DeltaMaths.UaddCarry(a.y, b.y, out var carryy);
            var resultz = DeltaMaths.UaddCarry(a.z, b.z, out var carryz);
            carry = new(carryx, carryy, carryz);
            return new(resultx, resulty, resultz);
        }

        public static uint3 UsubBorrow(uint3 a, uint3 b, out uint3 borrow)
        {
            var resultx = DeltaMaths.UsubBorrow(a.x, b.x, out var borrowx);
            var resulty = DeltaMaths.UsubBorrow(a.y, b.y, out var borrowy);
            var resultz = DeltaMaths.UsubBorrow(a.z, b.z, out var borrowz);
            borrow = new(borrowx, borrowy, borrowz);
            return new(resultx, resulty, resultz);
        }

        public static void UmulExtended(uint3 a, uint3 b, out uint3 msb, out uint3 lsb)
        {
            DeltaMaths.UmulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.UmulExtended(a.y, b.y, out var msby, out var lsby);
            DeltaMaths.UmulExtended(a.z, b.z, out var msbz, out var lsbz);
            msb = new(msbx, msby, msbz);
            lsb = new(lsbx, lsby, lsbz);
        }
    }
}
