// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct uint4
    {

        public static uint4 Min(uint4 a, uint4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static uint4 Min(uint4 a, uint b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static uint4 Min(uint a, uint4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static uint4 Max(uint4 a, uint4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static uint4 Max(uint4 a, uint b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static uint4 Max(uint a, uint4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static uint4 Clamp(uint4 value, uint min, uint max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static uint4 Clamp(uint4 value, uint4 min, uint4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static uint Sum(uint4 value)
        {
            return value.x + value.y + value.z + value.w;
        }

        public static int4 BitCount(uint4 value)
        {
            return new(DeltaMaths.BitCount(value.x), DeltaMaths.BitCount(value.y), DeltaMaths.BitCount(value.z), DeltaMaths.BitCount(value.w));
        }

        public static int4 FindLSB(uint4 value)
        {
            return new(DeltaMaths.FindLSB(value.x), DeltaMaths.FindLSB(value.y), DeltaMaths.FindLSB(value.z), DeltaMaths.FindLSB(value.w));
        }

        public static int4 FindMSB(uint4 value)
        {
            return new(DeltaMaths.FindMSB(value.x), DeltaMaths.FindMSB(value.y), DeltaMaths.FindMSB(value.z), DeltaMaths.FindMSB(value.w));
        }

        public static uint4 BitfieldReverse(uint4 value)
        {
            return new(DeltaMaths.BitfieldReverse(value.x), DeltaMaths.BitfieldReverse(value.y), DeltaMaths.BitfieldReverse(value.z), DeltaMaths.BitfieldReverse(value.w));
        }

        public static uint4 BitfieldExtract(uint4 value, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldExtract(value.x, offset, bits), DeltaMaths.BitfieldExtract(value.y, offset, bits), DeltaMaths.BitfieldExtract(value.z, offset, bits), DeltaMaths.BitfieldExtract(value.w, offset, bits));
        }

        public static uint4 BitfieldInsert(uint4 baseValue, uint4 insert, int offset, int bits)
        {
            return new(DeltaMaths.BitfieldInsert(baseValue.x, insert.x, offset, bits), DeltaMaths.BitfieldInsert(baseValue.y, insert.y, offset, bits), DeltaMaths.BitfieldInsert(baseValue.z, insert.z, offset, bits), DeltaMaths.BitfieldInsert(baseValue.w, insert.w, offset, bits));
        }

        public static uint4 UaddCarry(uint4 a, uint4 b, out uint4 carry)
        {
            var resultx = DeltaMaths.UaddCarry(a.x, b.x, out var carryx);
            var resulty = DeltaMaths.UaddCarry(a.y, b.y, out var carryy);
            var resultz = DeltaMaths.UaddCarry(a.z, b.z, out var carryz);
            var resultw = DeltaMaths.UaddCarry(a.w, b.w, out var carryw);
            carry = new(carryx, carryy, carryz, carryw);
            return new(resultx, resulty, resultz, resultw);
        }

        public static uint4 UsubBorrow(uint4 a, uint4 b, out uint4 borrow)
        {
            var resultx = DeltaMaths.UsubBorrow(a.x, b.x, out var borrowx);
            var resulty = DeltaMaths.UsubBorrow(a.y, b.y, out var borrowy);
            var resultz = DeltaMaths.UsubBorrow(a.z, b.z, out var borrowz);
            var resultw = DeltaMaths.UsubBorrow(a.w, b.w, out var borroww);
            borrow = new(borrowx, borrowy, borrowz, borroww);
            return new(resultx, resulty, resultz, resultw);
        }

        public static void UmulExtended(uint4 a, uint4 b, out uint4 msb, out uint4 lsb)
        {
            DeltaMaths.UmulExtended(a.x, b.x, out var msbx, out var lsbx);
            DeltaMaths.UmulExtended(a.y, b.y, out var msby, out var lsby);
            DeltaMaths.UmulExtended(a.z, b.z, out var msbz, out var lsbz);
            DeltaMaths.UmulExtended(a.w, b.w, out var msbw, out var lsbw);
            msb = new(msbx, msby, msbz, msbw);
            lsb = new(lsbx, lsby, lsbz, lsbw);
        }
    }
}
