#!/usr/bin/env python3
"""Generate one small conformance case for every supported contract overload."""

import json
from pathlib import Path


root = Path(__file__).resolve().parents[2]
manifest_path = root / "Vectors" / "shader-contract.json"
output_path = Path(__file__).resolve().parent / "GeneratedShaderContractCases.cs"

with manifest_path.open(encoding="utf-8") as manifest_file:
    manifest = json.load(manifest_file)

functions = [
    function
    for function in manifest["functions"]
    if function["mapping"] != "Unsupported"
]

lines = [
    "// <auto-generated />",
    "#nullable enable",
    "using System;",
    "",
    "namespace Delta.Maths.Conformance;",
    "",
    "internal static class GeneratedShaderContractCases",
    "{",
    f"    internal const int Count = {len(functions)};",
    "",
    "    internal static readonly string[] Identities =",
    "    [",
]

for function in functions:
    lines.append(f"        {json.dumps(function['identity'])},")

lines.extend(
    [
        "    ];",
        "",
        "    internal static void RunAll(ContractCaseRunner runner)",
        "    {",
    ]
)

for index in range(len(functions)):
    lines.append(f"        Case{index:04d}(runner);")

lines.extend(["    }", ""])

for index, function in enumerate(functions):
    lines.extend(
        [
            f"    private static void Case{index:04d}(ContractCaseRunner runner)",
            "    {",
            f"        runner.Run({json.dumps(function['identity'])});",
            "    }",
            "",
        ]
    )

lines.append("}")
output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {len(functions)} contract cases at {output_path}")
