// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DeltaMaths
{
    public partial struct double4
    {

        public static double4 Exp(double4 value)
        {
            return new(DeltaMaths.Exp(value.x), DeltaMaths.Exp(value.y), DeltaMaths.Exp(value.z), DeltaMaths.Exp(value.w));
        }

        public static double4 Exp2(double4 value)
        {
            return new(DeltaMaths.Exp2(value.x), DeltaMaths.Exp2(value.y), DeltaMaths.Exp2(value.z), DeltaMaths.Exp2(value.w));
        }

        public static double4 Log(double4 value)
        {
            return new(DeltaMaths.Log(value.x), DeltaMaths.Log(value.y), DeltaMaths.Log(value.z), DeltaMaths.Log(value.w));
        }

        public static double4 Log2(double4 value)
        {
            return new(DeltaMaths.Log2(value.x), DeltaMaths.Log2(value.y), DeltaMaths.Log2(value.z), DeltaMaths.Log2(value.w));
        }

        public static double4 Log10(double4 value)
        {
            return new(DeltaMaths.Log10(value.x), DeltaMaths.Log10(value.y), DeltaMaths.Log10(value.z), DeltaMaths.Log10(value.w));
        }

        public static double4 Sqrt(double4 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y), DeltaMaths.Sqrt(value.z), DeltaMaths.Sqrt(value.w));
        }

        public static double4 InverseSqrt(double4 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y), DeltaMaths.InverseSqrt(value.z), DeltaMaths.InverseSqrt(value.w));
        }

        public static double4 Cbrt(double4 value)
        {
            return new(DeltaMaths.Cbrt(value.x), DeltaMaths.Cbrt(value.y), DeltaMaths.Cbrt(value.z), DeltaMaths.Cbrt(value.w));
        }

        public static double4 Pow(double4 a, double4 b)
        {
            return new(DeltaMaths.Pow(a.x, b.x), DeltaMaths.Pow(a.y, b.y), DeltaMaths.Pow(a.z, b.z), DeltaMaths.Pow(a.w, b.w));
        }

        public static double4 Pow(double4 a, double b)
        {
            return new(DeltaMaths.Pow(a.x, b), DeltaMaths.Pow(a.y, b), DeltaMaths.Pow(a.z, b), DeltaMaths.Pow(a.w, b));
        }

        public static double4 Pow(double a, double4 b)
        {
            return new(DeltaMaths.Pow(a, b.x), DeltaMaths.Pow(a, b.y), DeltaMaths.Pow(a, b.z), DeltaMaths.Pow(a, b.w));
        }
    }
}
