// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DeltaMaths
{
    public partial struct double2
    {

        public static double Dot(double2 a, double2 b)
        {
            return a.x * b.x + a.y * b.y;
        }

        public static double SqrLength(double2 value)
        {
            return value.x * value.x + value.y * value.y;
        }

        public static double Length(double2 value)
        {
            return DeltaMaths.Sqrt(SqrLength(value));
        }

        public static double Distance(double2 a, double2 b)
        {
            return Length(a - b);
        }

        public static double SqrDistance(double2 a, double2 b)
        {
            return SqrLength(a - b);
        }

        public static double2 Normalize(double2 value)
        {
            return value / Length(value);
        }

        public static double2 NormalizeSafe(double2 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 2.2250738585072014E-308 ? zero : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static double2 NormalizeSafe(double2 value, double2 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 2.2250738585072014E-308 ? fallback : value * DeltaMaths.InverseSqrt(sqrLength);
        }

        public static double2 FaceForward(double2 N, double2 I, double2 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static double2 Reflect(double2 I, double2 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static double2 Refract(double2 I, double2 N, double eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + DeltaMaths.Sqrt(k)) * N;
        }

        public static double2 Project(double2 value, double2 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static double2 ProjectSafe(double2 value, double2 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static double2 ClampLength(double2 value, double maxLength)
        {
            maxLength = DeltaMaths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * DeltaMaths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static double2 MoveTowards(double2 current, double2 target, double maxDelta)
        {
            maxDelta = DeltaMaths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * DeltaMaths.InverseSqrt(sqrDistance);
        }

        public static double2 SmoothDamp(double2 source, double2 target, ref double2 velocity, double smoothTime, double deltaTime)
        {
            return new(DeltaMaths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), DeltaMaths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime));
        }
    }
}
