// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double2
    {

        public static double2 Min(double2 a, double2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static double2 Min(double2 a, double b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static double2 Min(double a, double2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static double2 Max(double2 a, double2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static double2 Max(double2 a, double b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static double2 Max(double a, double2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static double2 Clamp(double2 value, double min, double max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static double2 Clamp(double2 value, double2 min, double2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static double2 Abs(double2 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y));
        }

        public static double2 Sign(double2 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y));
        }

        public static double Sum(double2 value)
        {
            return value.x + value.y;
        }

        public static double2 Lerp(double2 a, double2 b, double t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t));
        }

        public static double2 Lerp(double2 a, double2 b, double2 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y));
        }

        public static double2 InvLerp(double2 edge0, double2 edge1, double2 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static double2 InvLerp(double2 edge0, double2 edge1, double value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value));
        }

        public static double2 Smoothstep(double2 edge0, double2 edge1, double2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0.x, edge1.x, value.x), DeltaMaths.Smoothstep(edge0.y, edge1.y, value.y));
        }

        public static double2 Smoothstep(double edge0, double edge1, double2 value)
        {
            return new(DeltaMaths.Smoothstep(edge0, edge1, value.x), DeltaMaths.Smoothstep(edge0, edge1, value.y));
        }

        public static double2 Step(double2 edge, double2 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y));
        }

        public static double2 Step(double edge, double2 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y));
        }

        public static double2 Saturate(double2 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y));
        }

        public static double2 Fma(double2 a, double2 b, double2 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y));
        }

        public static double2 Remap(double2 value, double2 sourceFrom, double2 sourceTo, double2 targetFrom, double2 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static double2 Floor(double2 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y));
        }

        public static double2 Ceil(double2 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y));
        }

        public static double2 Round(double2 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y));
        }

        public static double2 RoundEven(double2 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y));
        }

        public static double2 Truncate(double2 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y));
        }

        public static double2 Fract(double2 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y));
        }

        public static double2 Radians(double2 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y));
        }

        public static double2 Degrees(double2 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y));
        }
    }
}
