// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3
    {

        public static double3 Min(double3 a, double3 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z));
        }

        public static double3 Min(double3 a, double b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b));
        }

        public static double3 Min(double a, double3 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z));
        }

        public static double3 Max(double3 a, double3 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z));
        }

        public static double3 Max(double3 a, double b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b));
        }

        public static double3 Max(double a, double3 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z));
        }

        public static double3 Clamp(double3 value, double min, double max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max));
        }

        public static double3 Clamp(double3 value, double3 min, double3 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z));
        }

        public static double3 Abs(double3 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z));
        }

        public static double3 Sign(double3 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z));
        }

        public static double Sum(double3 value)
        {
            return value.x + value.y + value.z;
        }

        public static double3 Lerp(double3 a, double3 b, double t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t), DeltaMaths.Lerp(a.z, b.z, t));
        }

        public static double3 Lerp(double3 a, double3 b, double3 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y), DeltaMaths.Lerp(a.z, b.z, t.z));
        }

        public static double3 InvLerp(double3 edge0, double3 edge1, double3 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y), DeltaMaths.InvLerp(edge0.z, edge1.z, value.z));
        }

        public static double3 InvLerp(double3 edge0, double3 edge1, double value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value), DeltaMaths.InvLerp(edge0.z, edge1.z, value));
        }

        public static double3 SmoothStep(double3 edge0, double3 edge1, double3 value)
        {
            return new(DeltaMaths.SmoothStep(edge0.x, edge1.x, value.x), DeltaMaths.SmoothStep(edge0.y, edge1.y, value.y), DeltaMaths.SmoothStep(edge0.z, edge1.z, value.z));
        }

        public static double3 SmoothStep(double edge0, double edge1, double3 value)
        {
            return new(DeltaMaths.SmoothStep(edge0, edge1, value.x), DeltaMaths.SmoothStep(edge0, edge1, value.y), DeltaMaths.SmoothStep(edge0, edge1, value.z));
        }

        public static double3 Step(double3 edge, double3 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y), DeltaMaths.Step(edge.z, value.z));
        }

        public static double3 Step(double edge, double3 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y), DeltaMaths.Step(edge, value.z));
        }

        public static double3 Saturate(double3 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y), DeltaMaths.Saturate(value.z));
        }

        public static double3 Fma(double3 a, double3 b, double3 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y), DeltaMaths.Fma(a.z, b.z, c.z));
        }

        public static double3 Remap(double3 value, double3 sourceFrom, double3 sourceTo, double3 targetFrom, double3 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), DeltaMaths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z));
        }

        public static double3 Floor(double3 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y), DeltaMaths.Floor(value.z));
        }

        public static double3 Ceil(double3 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y), DeltaMaths.Ceil(value.z));
        }

        public static double3 Round(double3 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y), DeltaMaths.Round(value.z));
        }

        public static double3 RoundEven(double3 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y), DeltaMaths.RoundEven(value.z));
        }

        public static double3 Truncate(double3 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y), DeltaMaths.Truncate(value.z));
        }

        public static double3 Fract(double3 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y), DeltaMaths.Fract(value.z));
        }

        public static double3 Radians(double3 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y), DeltaMaths.Radians(value.z));
        }

        public static double3 Degrees(double3 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y), DeltaMaths.Degrees(value.z));
        }
    }
}
