// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DeltaMaths
{
    public partial struct double2
    {

        public static double2 Exp(double2 value)
        {
            return new(DeltaMaths.Exp(value.x), DeltaMaths.Exp(value.y));
        }

        public static double2 Exp2(double2 value)
        {
            return new(DeltaMaths.Exp2(value.x), DeltaMaths.Exp2(value.y));
        }

        public static double2 Log(double2 value)
        {
            return new(DeltaMaths.Log(value.x), DeltaMaths.Log(value.y));
        }

        public static double2 Log2(double2 value)
        {
            return new(DeltaMaths.Log2(value.x), DeltaMaths.Log2(value.y));
        }

        public static double2 Log10(double2 value)
        {
            return new(DeltaMaths.Log10(value.x), DeltaMaths.Log10(value.y));
        }

        public static double2 Sqrt(double2 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y));
        }

        public static double2 InverseSqrt(double2 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y));
        }

        public static double2 Cbrt(double2 value)
        {
            return new(DeltaMaths.Cbrt(value.x), DeltaMaths.Cbrt(value.y));
        }

        public static double2 Pow(double2 a, double2 b)
        {
            return new(DeltaMaths.Pow(a.x, b.x), DeltaMaths.Pow(a.y, b.y));
        }

        public static double2 Pow(double2 a, double b)
        {
            return new(DeltaMaths.Pow(a.x, b), DeltaMaths.Pow(a.y, b));
        }

        public static double2 Pow(double a, double2 b)
        {
            return new(DeltaMaths.Pow(a, b.x), DeltaMaths.Pow(a, b.y));
        }
    }
}
