// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct fix2
    {

        public static fix2 Min(fix2 a, fix2 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y));
        }

        public static fix2 Min(fix2 a, fix b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b));
        }

        public static fix2 Min(fix a, fix2 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y));
        }

        public static fix2 Max(fix2 a, fix2 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y));
        }

        public static fix2 Max(fix2 a, fix b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b));
        }

        public static fix2 Max(fix a, fix2 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y));
        }

        public static fix2 Clamp(fix2 value, fix min, fix max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max));
        }

        public static fix2 Clamp(fix2 value, fix2 min, fix2 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y));
        }

        public static fix2 Abs(fix2 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y));
        }

        public static fix2 Sign(fix2 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y));
        }

        public static fix Sum(fix2 value)
        {
            return value.x + value.y;
        }

        public static fix2 Lerp(fix2 a, fix2 b, fix t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t));
        }

        public static fix2 Lerp(fix2 a, fix2 b, fix2 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y));
        }

        public static fix2 InvLerp(fix2 edge0, fix2 edge1, fix2 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static fix2 InvLerp(fix2 edge0, fix2 edge1, fix value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value));
        }

        public static fix2 SmoothStep(fix2 edge0, fix2 edge1, fix2 value)
        {
            return new(DeltaMaths.SmoothStep(edge0.x, edge1.x, value.x), DeltaMaths.SmoothStep(edge0.y, edge1.y, value.y));
        }

        public static fix2 SmoothStep(fix edge0, fix edge1, fix2 value)
        {
            return new(DeltaMaths.SmoothStep(edge0, edge1, value.x), DeltaMaths.SmoothStep(edge0, edge1, value.y));
        }

        public static fix2 Step(fix2 edge, fix2 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y));
        }

        public static fix2 Step(fix edge, fix2 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y));
        }

        public static fix2 Saturate(fix2 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y));
        }

        public static fix2 Fma(fix2 a, fix2 b, fix2 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y));
        }

        public static fix2 Remap(fix2 value, fix2 sourceFrom, fix2 sourceTo, fix2 targetFrom, fix2 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static fix2 Floor(fix2 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y));
        }

        public static fix2 Ceil(fix2 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y));
        }

        public static fix2 Round(fix2 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y));
        }

        public static fix2 Truncate(fix2 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y));
        }

        public static fix2 Fract(fix2 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y));
        }

        public static fix2 Radians(fix2 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y));
        }

        public static fix2 Degrees(fix2 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y));
        }
    }
}
