// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct fix4
    {

        public static fix4 Min(fix4 a, fix4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static fix4 Min(fix4 a, fix b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static fix4 Min(fix a, fix4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static fix4 Max(fix4 a, fix4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static fix4 Max(fix4 a, fix b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static fix4 Max(fix a, fix4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static fix4 Clamp(fix4 value, fix min, fix max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static fix4 Clamp(fix4 value, fix4 min, fix4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static fix4 Abs(fix4 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z), DeltaMaths.Abs(value.w));
        }

        public static fix4 Sign(fix4 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z), DeltaMaths.Sign(value.w));
        }

        public static fix Sum(fix4 value)
        {
            return value.x + value.y + value.z + value.w;
        }

        public static fix4 Lerp(fix4 a, fix4 b, fix t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t), DeltaMaths.Lerp(a.z, b.z, t), DeltaMaths.Lerp(a.w, b.w, t));
        }

        public static fix4 Lerp(fix4 a, fix4 b, fix4 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y), DeltaMaths.Lerp(a.z, b.z, t.z), DeltaMaths.Lerp(a.w, b.w, t.w));
        }

        public static fix4 InvLerp(fix4 edge0, fix4 edge1, fix4 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y), DeltaMaths.InvLerp(edge0.z, edge1.z, value.z), DeltaMaths.InvLerp(edge0.w, edge1.w, value.w));
        }

        public static fix4 InvLerp(fix4 edge0, fix4 edge1, fix value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value), DeltaMaths.InvLerp(edge0.z, edge1.z, value), DeltaMaths.InvLerp(edge0.w, edge1.w, value));
        }

        public static fix4 SmoothStep(fix4 edge0, fix4 edge1, fix4 value)
        {
            return new(DeltaMaths.SmoothStep(edge0.x, edge1.x, value.x), DeltaMaths.SmoothStep(edge0.y, edge1.y, value.y), DeltaMaths.SmoothStep(edge0.z, edge1.z, value.z), DeltaMaths.SmoothStep(edge0.w, edge1.w, value.w));
        }

        public static fix4 SmoothStep(fix edge0, fix edge1, fix4 value)
        {
            return new(DeltaMaths.SmoothStep(edge0, edge1, value.x), DeltaMaths.SmoothStep(edge0, edge1, value.y), DeltaMaths.SmoothStep(edge0, edge1, value.z), DeltaMaths.SmoothStep(edge0, edge1, value.w));
        }

        public static fix4 Step(fix4 edge, fix4 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y), DeltaMaths.Step(edge.z, value.z), DeltaMaths.Step(edge.w, value.w));
        }

        public static fix4 Step(fix edge, fix4 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y), DeltaMaths.Step(edge, value.z), DeltaMaths.Step(edge, value.w));
        }

        public static fix4 Saturate(fix4 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y), DeltaMaths.Saturate(value.z), DeltaMaths.Saturate(value.w));
        }

        public static fix4 Fma(fix4 a, fix4 b, fix4 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y), DeltaMaths.Fma(a.z, b.z, c.z), DeltaMaths.Fma(a.w, b.w, c.w));
        }

        public static fix4 Remap(fix4 value, fix4 sourceFrom, fix4 sourceTo, fix4 targetFrom, fix4 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), DeltaMaths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z), DeltaMaths.Remap(value.w, sourceFrom.w, sourceTo.w, targetFrom.w, targetTo.w));
        }

        public static fix4 Floor(fix4 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y), DeltaMaths.Floor(value.z), DeltaMaths.Floor(value.w));
        }

        public static fix4 Ceil(fix4 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y), DeltaMaths.Ceil(value.z), DeltaMaths.Ceil(value.w));
        }

        public static fix4 Round(fix4 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y), DeltaMaths.Round(value.z), DeltaMaths.Round(value.w));
        }

        public static fix4 Truncate(fix4 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y), DeltaMaths.Truncate(value.z), DeltaMaths.Truncate(value.w));
        }

        public static fix4 Fract(fix4 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y), DeltaMaths.Fract(value.z), DeltaMaths.Fract(value.w));
        }

        public static fix4 Radians(fix4 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y), DeltaMaths.Radians(value.z), DeltaMaths.Radians(value.w));
        }

        public static fix4 Degrees(fix4 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y), DeltaMaths.Degrees(value.z), DeltaMaths.Degrees(value.w));
        }
    }
}
