// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DeltaMaths
{
    public partial struct fix4
    {

        public static fix4 Sqrt(fix4 value)
        {
            return new(DeltaMaths.Sqrt(value.x), DeltaMaths.Sqrt(value.y), DeltaMaths.Sqrt(value.z), DeltaMaths.Sqrt(value.w));
        }

        public static fix4 InverseSqrt(fix4 value)
        {
            return new(DeltaMaths.InverseSqrt(value.x), DeltaMaths.InverseSqrt(value.y), DeltaMaths.InverseSqrt(value.z), DeltaMaths.InverseSqrt(value.w));
        }
    }
}
