// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float4
    {

        public static float4 Min(float4 a, float4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static float4 Min(float4 a, float b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static float4 Min(float a, float4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static float4 Max(float4 a, float4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static float4 Max(float4 a, float b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static float4 Max(float a, float4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static float4 Clamp(float4 value, float min, float max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static float4 Clamp(float4 value, float4 min, float4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static float4 Abs(float4 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z), DeltaMaths.Abs(value.w));
        }

        public static float4 Sign(float4 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z), DeltaMaths.Sign(value.w));
        }

        public static float Sum(float4 value)
        {
            return value.x + value.y + value.z + value.w;
        }

        public static float4 Lerp(float4 a, float4 b, float t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t), DeltaMaths.Lerp(a.z, b.z, t), DeltaMaths.Lerp(a.w, b.w, t));
        }

        public static float4 Lerp(float4 a, float4 b, float4 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y), DeltaMaths.Lerp(a.z, b.z, t.z), DeltaMaths.Lerp(a.w, b.w, t.w));
        }

        public static float4 InvLerp(float4 edge0, float4 edge1, float4 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y), DeltaMaths.InvLerp(edge0.z, edge1.z, value.z), DeltaMaths.InvLerp(edge0.w, edge1.w, value.w));
        }

        public static float4 InvLerp(float4 edge0, float4 edge1, float value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value), DeltaMaths.InvLerp(edge0.z, edge1.z, value), DeltaMaths.InvLerp(edge0.w, edge1.w, value));
        }

        public static float4 Smoothstep(float4 edge0, float4 edge1, float4 value)
        {
            return new(DeltaMaths.Smoothstep(edge0.x, edge1.x, value.x), DeltaMaths.Smoothstep(edge0.y, edge1.y, value.y), DeltaMaths.Smoothstep(edge0.z, edge1.z, value.z), DeltaMaths.Smoothstep(edge0.w, edge1.w, value.w));
        }

        public static float4 Smoothstep(float edge0, float edge1, float4 value)
        {
            return new(DeltaMaths.Smoothstep(edge0, edge1, value.x), DeltaMaths.Smoothstep(edge0, edge1, value.y), DeltaMaths.Smoothstep(edge0, edge1, value.z), DeltaMaths.Smoothstep(edge0, edge1, value.w));
        }

        public static float4 Step(float4 edge, float4 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y), DeltaMaths.Step(edge.z, value.z), DeltaMaths.Step(edge.w, value.w));
        }

        public static float4 Step(float edge, float4 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y), DeltaMaths.Step(edge, value.z), DeltaMaths.Step(edge, value.w));
        }

        public static float4 Saturate(float4 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y), DeltaMaths.Saturate(value.z), DeltaMaths.Saturate(value.w));
        }

        public static float4 Fma(float4 a, float4 b, float4 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y), DeltaMaths.Fma(a.z, b.z, c.z), DeltaMaths.Fma(a.w, b.w, c.w));
        }

        public static float4 Remap(float4 value, float4 sourceFrom, float4 sourceTo, float4 targetFrom, float4 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), DeltaMaths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z), DeltaMaths.Remap(value.w, sourceFrom.w, sourceTo.w, targetFrom.w, targetTo.w));
        }

        public static float4 Mod(float4 x, float4 y)
        {
            return new(DeltaMaths.Mod(x.x, y.x), DeltaMaths.Mod(x.y, y.y), DeltaMaths.Mod(x.z, y.z), DeltaMaths.Mod(x.w, y.w));
        }

        public static float4 Mod(float4 x, float y)
        {
            return new(DeltaMaths.Mod(x.x, y), DeltaMaths.Mod(x.y, y), DeltaMaths.Mod(x.z, y), DeltaMaths.Mod(x.w, y));
        }

        public static float4 Floor(float4 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y), DeltaMaths.Floor(value.z), DeltaMaths.Floor(value.w));
        }

        public static float4 Ceil(float4 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y), DeltaMaths.Ceil(value.z), DeltaMaths.Ceil(value.w));
        }

        public static float4 Round(float4 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y), DeltaMaths.Round(value.z), DeltaMaths.Round(value.w));
        }

        public static float4 RoundEven(float4 value)
        {
            return new(DeltaMaths.RoundEven(value.x), DeltaMaths.RoundEven(value.y), DeltaMaths.RoundEven(value.z), DeltaMaths.RoundEven(value.w));
        }

        public static float4 Truncate(float4 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y), DeltaMaths.Truncate(value.z), DeltaMaths.Truncate(value.w));
        }

        public static float4 Fract(float4 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y), DeltaMaths.Fract(value.z), DeltaMaths.Fract(value.w));
        }

        public static float4 Radians(float4 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y), DeltaMaths.Radians(value.z), DeltaMaths.Radians(value.w));
        }

        public static float4 Degrees(float4 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y), DeltaMaths.Degrees(value.z), DeltaMaths.Degrees(value.w));
        }
    }
}
