// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float3
    {

        public static float3 Min(float3 a, float3 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z));
        }

        public static float3 Min(float3 a, float b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b));
        }

        public static float3 Min(float a, float3 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z));
        }

        public static float3 Max(float3 a, float3 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z));
        }

        public static float3 Max(float3 a, float b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b));
        }

        public static float3 Max(float a, float3 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z));
        }

        public static float3 Clamp(float3 value, float min, float max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max));
        }

        public static float3 Clamp(float3 value, float3 min, float3 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z));
        }

        public static float3 Abs(float3 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z));
        }

        public static float3 Sign(float3 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z));
        }

        public static float Sum(float3 value)
        {
            return value.x + value.y + value.z;
        }

        public static float3 Lerp(float3 a, float3 b, float t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t), DeltaMaths.Lerp(a.y, b.y, t), DeltaMaths.Lerp(a.z, b.z, t));
        }

        public static float3 Lerp(float3 a, float3 b, float3 t)
        {
            return new(DeltaMaths.Lerp(a.x, b.x, t.x), DeltaMaths.Lerp(a.y, b.y, t.y), DeltaMaths.Lerp(a.z, b.z, t.z));
        }

        public static float3 InvLerp(float3 edge0, float3 edge1, float3 value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value.x), DeltaMaths.InvLerp(edge0.y, edge1.y, value.y), DeltaMaths.InvLerp(edge0.z, edge1.z, value.z));
        }

        public static float3 InvLerp(float3 edge0, float3 edge1, float value)
        {
            return new(DeltaMaths.InvLerp(edge0.x, edge1.x, value), DeltaMaths.InvLerp(edge0.y, edge1.y, value), DeltaMaths.InvLerp(edge0.z, edge1.z, value));
        }

        public static float3 SmoothStep(float3 edge0, float3 edge1, float3 value)
        {
            return new(DeltaMaths.SmoothStep(edge0.x, edge1.x, value.x), DeltaMaths.SmoothStep(edge0.y, edge1.y, value.y), DeltaMaths.SmoothStep(edge0.z, edge1.z, value.z));
        }

        public static float3 SmoothStep(float edge0, float edge1, float3 value)
        {
            return new(DeltaMaths.SmoothStep(edge0, edge1, value.x), DeltaMaths.SmoothStep(edge0, edge1, value.y), DeltaMaths.SmoothStep(edge0, edge1, value.z));
        }

        public static float3 Step(float3 edge, float3 value)
        {
            return new(DeltaMaths.Step(edge.x, value.x), DeltaMaths.Step(edge.y, value.y), DeltaMaths.Step(edge.z, value.z));
        }

        public static float3 Step(float edge, float3 value)
        {
            return new(DeltaMaths.Step(edge, value.x), DeltaMaths.Step(edge, value.y), DeltaMaths.Step(edge, value.z));
        }

        public static float3 Saturate(float3 value)
        {
            return new(DeltaMaths.Saturate(value.x), DeltaMaths.Saturate(value.y), DeltaMaths.Saturate(value.z));
        }

        public static float3 Fma(float3 a, float3 b, float3 c)
        {
            return new(DeltaMaths.Fma(a.x, b.x, c.x), DeltaMaths.Fma(a.y, b.y, c.y), DeltaMaths.Fma(a.z, b.z, c.z));
        }

        public static float3 Remap(float3 value, float3 sourceFrom, float3 sourceTo, float3 targetFrom, float3 targetTo)
        {
            return new(DeltaMaths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), DeltaMaths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), DeltaMaths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z));
        }

        public static float3 Mod(float3 x, float3 y)
        {
            return new(DeltaMaths.Mod(x.x, y.x), DeltaMaths.Mod(x.y, y.y), DeltaMaths.Mod(x.z, y.z));
        }

        public static float3 Mod(float3 x, float y)
        {
            return new(DeltaMaths.Mod(x.x, y), DeltaMaths.Mod(x.y, y), DeltaMaths.Mod(x.z, y));
        }

        public static float3 Floor(float3 value)
        {
            return new(DeltaMaths.Floor(value.x), DeltaMaths.Floor(value.y), DeltaMaths.Floor(value.z));
        }

        public static float3 Ceil(float3 value)
        {
            return new(DeltaMaths.Ceil(value.x), DeltaMaths.Ceil(value.y), DeltaMaths.Ceil(value.z));
        }

        public static float3 Round(float3 value)
        {
            return new(DeltaMaths.Round(value.x), DeltaMaths.Round(value.y), DeltaMaths.Round(value.z));
        }

        public static float3 Truncate(float3 value)
        {
            return new(DeltaMaths.Truncate(value.x), DeltaMaths.Truncate(value.y), DeltaMaths.Truncate(value.z));
        }

        public static float3 Fract(float3 value)
        {
            return new(DeltaMaths.Fract(value.x), DeltaMaths.Fract(value.y), DeltaMaths.Fract(value.z));
        }

        public static float3 Radians(float3 value)
        {
            return new(DeltaMaths.Radians(value.x), DeltaMaths.Radians(value.y), DeltaMaths.Radians(value.z));
        }

        public static float3 Degrees(float3 value)
        {
            return new(DeltaMaths.Degrees(value.x), DeltaMaths.Degrees(value.y), DeltaMaths.Degrees(value.z));
        }
    }
}
