// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct int4
    {

        public static int4 Min(int4 a, int4 b)
        {
            return new(DeltaMaths.Min(a.x, b.x), DeltaMaths.Min(a.y, b.y), DeltaMaths.Min(a.z, b.z), DeltaMaths.Min(a.w, b.w));
        }

        public static int4 Min(int4 a, int b)
        {
            return new(DeltaMaths.Min(a.x, b), DeltaMaths.Min(a.y, b), DeltaMaths.Min(a.z, b), DeltaMaths.Min(a.w, b));
        }

        public static int4 Min(int a, int4 b)
        {
            return new(DeltaMaths.Min(a, b.x), DeltaMaths.Min(a, b.y), DeltaMaths.Min(a, b.z), DeltaMaths.Min(a, b.w));
        }

        public static int4 Max(int4 a, int4 b)
        {
            return new(DeltaMaths.Max(a.x, b.x), DeltaMaths.Max(a.y, b.y), DeltaMaths.Max(a.z, b.z), DeltaMaths.Max(a.w, b.w));
        }

        public static int4 Max(int4 a, int b)
        {
            return new(DeltaMaths.Max(a.x, b), DeltaMaths.Max(a.y, b), DeltaMaths.Max(a.z, b), DeltaMaths.Max(a.w, b));
        }

        public static int4 Max(int a, int4 b)
        {
            return new(DeltaMaths.Max(a, b.x), DeltaMaths.Max(a, b.y), DeltaMaths.Max(a, b.z), DeltaMaths.Max(a, b.w));
        }

        public static int4 Clamp(int4 value, int min, int max)
        {
            return new(DeltaMaths.Clamp(value.x, min, max), DeltaMaths.Clamp(value.y, min, max), DeltaMaths.Clamp(value.z, min, max), DeltaMaths.Clamp(value.w, min, max));
        }

        public static int4 Clamp(int4 value, int4 min, int4 max)
        {
            return new(DeltaMaths.Clamp(value.x, min.x, max.x), DeltaMaths.Clamp(value.y, min.y, max.y), DeltaMaths.Clamp(value.z, min.z, max.z), DeltaMaths.Clamp(value.w, min.w, max.w));
        }

        public static int4 Abs(int4 value)
        {
            return new(DeltaMaths.Abs(value.x), DeltaMaths.Abs(value.y), DeltaMaths.Abs(value.z), DeltaMaths.Abs(value.w));
        }

        public static int4 Sign(int4 value)
        {
            return new(DeltaMaths.Sign(value.x), DeltaMaths.Sign(value.y), DeltaMaths.Sign(value.z), DeltaMaths.Sign(value.w));
        }

        public static int Sum(int4 value)
        {
            return value.x + value.y + value.z + value.w;
        }
    }
}
